"""Drift-guard tests for _RECON_REPORT_TOOL_GUIDANCE (task-2559).

_RECON_REPORT_TOOL_GUIDANCE (reconciliation/prompts/__init__.py) is generated
from live recon_report FastMCP tool signatures via
render_recon_report_tool_guidance() rather than hand-transcribed, because
hand-maintenance drifted twice — most recently, every example omitted the
required `run_id` kwarg, undetected across a full reviewer round.

This module asserts:
- every report-tool call example in the fully ASSEMBLED stage prompts
  (bare inline examples included, not just the generated guidance block)
  shows `run_id` — this is the only way to catch hand-written inline
  examples like stage2.py's cross-project routing snippets or stage3.py's
  verification pseudocode, which render_recon_report_tool_guidance() never
  touches.

A minimal smoke test also confirms render_recon_report_tool_guidance() runs
cleanly and produces non-empty text. It deliberately does not re-introspect
live signatures or pin call-shape substrings — those would be tautological,
since the shipped guidance is generated by iterating the exact same live
signatures such a test would re-check, so the assertions could not fail
short of import already having fallen back.

start_report is harness-called (agents never call it themselves) and is
intentionally excluded — see reconciliation/prompts/__init__.py.
"""
from __future__ import annotations

import logging
import re

import pytest

from fused_memory.reconciliation import prompts as prompts_module
from fused_memory.reconciliation.prompts import (
    _RECON_REPORT_TOOL_GUIDANCE_FALLBACK,
    get_recon_report_tool_guidance,
    render_recon_report_tool_guidance,
)
from fused_memory.reconciliation.prompts.stage1 import STAGE1_SYSTEM_PROMPT
from fused_memory.reconciliation.prompts.stage2 import (
    STAGE2_SYSTEM_PROMPT,
    build_stage2_system_prompt,
)
from fused_memory.reconciliation.prompts.stage3 import STAGE3_SYSTEM_PROMPT

# Agent-called report tools (excludes start_report — harness-called).
_AGENT_CALLED_REPORT_TOOLS = (
    'add_finding',
    'set_stat',
    'inc_stat',
    'complete',
    'cite_entity',
    'cite_edge',
    'cite_task',
    'cite_memory',
    'cite_run',
)


def _iter_call_openers(text: str, tool_name: str):
    """Yield the index of the opening '(' for every *tool_name* call in *text*.

    Matches both the bare form (``tool_name(``) and the
    ``mcp__recon-report__``-prefixed form (``mcp__recon-report__tool_name(``),
    as long as the call opener is not itself embedded inside a longer
    identifier — i.e. the character immediately before the match (before
    the prefix, if present, otherwise before the bare name) must not be an
    identifier character.
    """
    pattern = re.compile(r'(?<![A-Za-z0-9_])(?:mcp__recon-report__)?' + re.escape(tool_name) + r'\(')
    for m in pattern.finditer(text):
        yield m.end() - 1


def _extract_call_args_at(text: str, paren_idx: int) -> str:
    """Return the balanced-paren argument substring starting at *paren_idx* ('(')."""
    assert text[paren_idx] == '('
    depth = 0
    for i in range(paren_idx, len(text)):
        if text[i] == '(':
            depth += 1
        elif text[i] == ')':
            depth -= 1
            if depth == 0:
                return text[paren_idx + 1 : i]
    raise AssertionError(f'Unbalanced parens scanning from index {paren_idx}')


class TestReconReportGuidanceDrift:
    """render_recon_report_tool_guidance() runs cleanly and produces real guidance."""

    def test_render_returns_non_empty_string(self):
        """Smoke test: rendering the guidance succeeds and yields non-empty text.

        Deliberately does not re-introspect live signatures or pin call-shape
        substrings — the shipped guidance is generated by iterating the exact
        same live signatures such assertions would re-check, so they would be
        tautological (unable to fail short of import already having fallen
        back).
        """
        result = render_recon_report_tool_guidance()
        assert isinstance(result, str)
        assert result


# Fully assembled stage-prompt texts to scan for inline report-tool call examples.
# build_stage2_system_prompt('autopilot_video') is included because it injects
# AUTOPILOT_VIDEO_CONTAMINATION_GUARDRAIL, which carries its own cross-project
# add_finding example only present under that project_id — the plain
# STAGE2_SYSTEM_PROMPT / build_stage2_system_prompt('dark_factory') texts never
# surface it.
_ASSEMBLED_PROMPT_CASES = (
    ('STAGE1_SYSTEM_PROMPT', STAGE1_SYSTEM_PROMPT),
    ('STAGE2_SYSTEM_PROMPT', STAGE2_SYSTEM_PROMPT),
    ('STAGE3_SYSTEM_PROMPT', STAGE3_SYSTEM_PROMPT),
    ("build_stage2_system_prompt('dark_factory')", build_stage2_system_prompt('dark_factory')),
    ("build_stage2_system_prompt('autopilot_video')", build_stage2_system_prompt('autopilot_video')),
)


class TestReconReportRunIdGuardOverAssembledPrompts:
    """Every report-tool call example in the ASSEMBLED stage prompts shows run_id.

    render_recon_report_tool_guidance() (see TestReconReportGuidanceDrift above)
    only generates the shared guidance block — it cannot reach hand-written
    inline examples elsewhere in a stage prompt. This class scans the fully
    assembled prompt TEXT (not source files) for every report-tool call opener,
    bare or `mcp__recon-report__`-prefixed, and asserts each one's argument
    list carries `run_id`. This covers stage2.py's cross-project routing
    examples, stage3.py's verification pseudocode, and the autopilot_video.py
    contamination-guardrail example.

    Scanning assembled prompt text (rather than source modules) means
    recon_self_model.MCP_CALL_SIGNATURES — verified never rendered into any
    stage prompt, and task 2231's (W5-ξ) domain — cannot be matched here.

    start_report is harness-called (agents never call it themselves) and is
    intentionally excluded, as in TestReconReportGuidanceDrift.
    """

    @pytest.mark.parametrize(
        'prompt_label,prompt_text',
        _ASSEMBLED_PROMPT_CASES,
        ids=[label for label, _ in _ASSEMBLED_PROMPT_CASES],
    )
    def test_every_report_tool_call_example_shows_run_id(self, prompt_label, prompt_text):
        for tool_name in _AGENT_CALLED_REPORT_TOOLS:
            for paren_idx in _iter_call_openers(prompt_text, tool_name):
                args_substr = _extract_call_args_at(prompt_text, paren_idx)
                assert 'run_id' in args_substr, (
                    f'{prompt_label}: a `{tool_name}(...)` call example is missing '
                    f'`run_id` — got: {tool_name}({args_substr})'
                )


class TestReconReportGuidanceFallback:
    """get_recon_report_tool_guidance()'s exception/fallback branch (reviewer finding).

    _RECON_REPORT_TOOL_GUIDANCE_FALLBACK exists specifically as a run_id-safe
    safety net for when render_recon_report_tool_guidance() raises (e.g. a
    FastMCP internals change). Unlike the generated path, it is hand-written
    and was previously never exercised by a test nor scanned for the very
    run_id-omission drift this task set out to eliminate. This class covers
    both gaps.
    """

    def setup_method(self):
        # get_recon_report_tool_guidance() is backed by the lru_cache'd
        # _cached_recon_report_tool_guidance() helper — clear it so tests
        # don't observe each other's cached renders.
        prompts_module._cached_recon_report_tool_guidance.cache_clear()

    def teardown_method(self):
        prompts_module._cached_recon_report_tool_guidance.cache_clear()

    def test_falls_back_and_logs_when_render_raises(self, monkeypatch, caplog):
        """A raising get_recon_report_tool_signatures() forces the frozen fallback."""

        def _raise():
            raise RuntimeError('FastMCP tool-manager internals changed shape')

        monkeypatch.setattr(
            'fused_memory.server.recon_report.get_recon_report_tool_signatures', _raise
        )
        with caplog.at_level(logging.ERROR):
            result = get_recon_report_tool_guidance()

        assert result == _RECON_REPORT_TOOL_GUIDANCE_FALLBACK
        error_records = [r for r in caplog.records if r.levelno == logging.ERROR]
        assert any('falling back' in r.message for r in error_records), (
            f'Expected an ERROR log containing "falling back", got: '
            f'{[r.message for r in error_records]}'
        )

    def test_self_heals_on_next_call_after_transient_failure(self, monkeypatch):
        """A transient failure must not be cached — the next call retries live.

        Regression guard for the reviewer's robustness finding: because the
        fallback path is deliberately NOT memoized (only a successful render
        is, via _cached_recon_report_tool_guidance), a call made after the
        introspection failure clears should get the real generated guidance
        again in the SAME process, not the frozen fallback forever.
        """

        def _raise():
            raise RuntimeError('transient hiccup')

        monkeypatch.setattr(
            'fused_memory.server.recon_report.get_recon_report_tool_signatures', _raise
        )
        assert get_recon_report_tool_guidance() == _RECON_REPORT_TOOL_GUIDANCE_FALLBACK

        monkeypatch.undo()
        healed = get_recon_report_tool_guidance()
        assert healed == render_recon_report_tool_guidance()
        assert healed != _RECON_REPORT_TOOL_GUIDANCE_FALLBACK

    def test_fallback_call_examples_all_carry_run_id(self):
        """Guard the frozen fallback string with the same run_id scan used above.

        The fallback is hand-written and unlike the generated path is never
        re-verified against live signatures — this pins it against the exact
        drift bug (a call example silently missing `run_id`) this task exists
        to eliminate.
        """
        for tool_name in _AGENT_CALLED_REPORT_TOOLS:
            for paren_idx in _iter_call_openers(_RECON_REPORT_TOOL_GUIDANCE_FALLBACK, tool_name):
                args_substr = _extract_call_args_at(
                    _RECON_REPORT_TOOL_GUIDANCE_FALLBACK, paren_idx
                )
                assert 'run_id' in args_substr, (
                    f'fallback: a `{tool_name}(...)` call example is missing '
                    f'`run_id` — got: {tool_name}({args_substr})'
                )
