"""Drift-guard tests for _RECON_REPORT_TOOL_GUIDANCE (task-2559).

_RECON_REPORT_TOOL_GUIDANCE (reconciliation/prompts/__init__.py) is generated
from live recon_report FastMCP tool signatures via
render_recon_report_tool_guidance() rather than hand-transcribed, because
hand-maintenance drifted twice — most recently, every example omitted the
required `run_id` kwarg, undetected across a full reviewer round.

This module asserts:
- every report-tool call example in the fully ASSEMBLED stage prompts
  (bare inline examples included, not just the generated guidance block)
  shows `run_id` — this is the only way to catch hand-written inline
  examples like stage2.py's cross-project routing snippets or stage3.py's
  verification pseudocode, which render_recon_report_tool_guidance() never
  touches.
- _frozen_recon_report_tool_guidance() — rendered lazily (reviewer robustness
  finding: NOT at module-import time, so a bad snapshot edit cannot become an
  ImportError for every consumer of the `prompts` package) from
  _FROZEN_RECON_REPORT_SIGNATURE_SPECS through the same template and
  render_call() as the live guidance — equals render_recon_report_tool_guidance(),
  and the frozen signature snapshot matches the live tool signatures (name,
  order, required-ness, and tool-set coverage in both directions). See
  TestFallbackIsDerivedFromTheSameRenderer.

A minimal smoke test also confirms render_recon_report_tool_guidance() runs
cleanly and produces non-empty text. For that GENERATED path specifically,
the module deliberately does not re-introspect live signatures or pin
call-shape substrings on its output: those would be tautological, since the
shipped guidance is generated by iterating the exact same live signatures
such a test would re-check, so the assertions could not fail short of import
already having fallen back. TestFallbackIsDerivedFromTheSameRenderer is
different in kind, not degree: it compares two RENDERS FROM DIFFERENT
SIGNATURE SOURCES — the frozen snapshot vs. live introspection — rather than
re-checking generated text against the signatures that generated it, so it
can genuinely fail when the snapshot drifts.

TestReconReportGuidanceFallback's test_fallback_call_examples_all_carry_run_id
run_id scan is now satisfied by construction (the fallback is generated, and
run_id is required in the snapshot for every tool) — it is retained as a
cheap belt-and-braces guard on the original task-2559 bug, not as the
mechanism that now prevents drift; do not mistake it for one.

start_report is harness-called (agents never call it themselves) and is
intentionally excluded — see reconciliation/prompts/__init__.py.
"""
from __future__ import annotations

import inspect
import logging
import re

import pytest

from fused_memory.reconciliation import prompts as prompts_module
from fused_memory.reconciliation.prompts import (
    _FROZEN_RECON_REPORT_SIGNATURE_SPECS,
    _frozen_recon_report_tool_guidance,
    get_recon_report_tool_guidance,
    render_recon_report_tool_guidance,
)
from fused_memory.reconciliation.prompts.stage1 import STAGE1_SYSTEM_PROMPT
from fused_memory.reconciliation.prompts.stage2 import (
    STAGE2_SYSTEM_PROMPT,
    build_stage2_system_prompt,
)
from fused_memory.reconciliation.prompts.stage3 import STAGE3_SYSTEM_PROMPT
from fused_memory.server.recon_report import get_recon_report_tool_signatures

# Agent-called report tools (excludes start_report — harness-called).
_AGENT_CALLED_REPORT_TOOLS = (
    'add_finding',
    'set_stat',
    'inc_stat',
    'complete',
    'cite_entity',
    'cite_edge',
    'cite_task',
    'cite_memory',
    'cite_run',
)


def _iter_call_openers(text: str, tool_name: str):
    """Yield the index of the opening '(' for every *tool_name* call in *text*.

    Matches both the bare form (``tool_name(``) and the
    ``mcp__recon-report__``-prefixed form (``mcp__recon-report__tool_name(``),
    as long as the call opener is not itself embedded inside a longer
    identifier — i.e. the character immediately before the match (before
    the prefix, if present, otherwise before the bare name) must not be an
    identifier character.
    """
    pattern = re.compile(r'(?<![A-Za-z0-9_])(?:mcp__recon-report__)?' + re.escape(tool_name) + r'\(')
    for m in pattern.finditer(text):
        yield m.end() - 1


def _extract_call_args_at(text: str, paren_idx: int) -> str:
    """Return the balanced-paren argument substring starting at *paren_idx* ('(')."""
    assert text[paren_idx] == '('
    depth = 0
    for i in range(paren_idx, len(text)):
        if text[i] == '(':
            depth += 1
        elif text[i] == ')':
            depth -= 1
            if depth == 0:
                return text[paren_idx + 1 : i]
    raise AssertionError(f'Unbalanced parens scanning from index {paren_idx}')


class TestReconReportGuidanceDrift:
    """render_recon_report_tool_guidance() runs cleanly and produces real guidance."""

    def test_render_returns_non_empty_string(self):
        """Smoke test: rendering the guidance succeeds and yields non-empty text.

        Deliberately does not re-introspect live signatures or pin call-shape
        substrings — the shipped guidance is generated by iterating the exact
        same live signatures such assertions would re-check, so they would be
        tautological (unable to fail short of import already having fallen
        back).
        """
        result = render_recon_report_tool_guidance()
        assert isinstance(result, str)
        assert result


# Fully assembled stage-prompt texts to scan for inline report-tool call examples.
# build_stage2_system_prompt('autopilot_video') is included because it injects
# AUTOPILOT_VIDEO_CONTAMINATION_GUARDRAIL, which carries its own cross-project
# add_finding example only present under that project_id — the plain
# STAGE2_SYSTEM_PROMPT / build_stage2_system_prompt('dark_factory') texts never
# surface it.
_ASSEMBLED_PROMPT_CASES = (
    ('STAGE1_SYSTEM_PROMPT', STAGE1_SYSTEM_PROMPT),
    ('STAGE2_SYSTEM_PROMPT', STAGE2_SYSTEM_PROMPT),
    ('STAGE3_SYSTEM_PROMPT', STAGE3_SYSTEM_PROMPT),
    ("build_stage2_system_prompt('dark_factory')", build_stage2_system_prompt('dark_factory')),
    ("build_stage2_system_prompt('autopilot_video')", build_stage2_system_prompt('autopilot_video')),
)


class TestReconReportRunIdGuardOverAssembledPrompts:
    """Every report-tool call example in the ASSEMBLED stage prompts shows run_id.

    render_recon_report_tool_guidance() (see TestReconReportGuidanceDrift above)
    only generates the shared guidance block — it cannot reach hand-written
    inline examples elsewhere in a stage prompt. This class scans the fully
    assembled prompt TEXT (not source files) for every report-tool call opener,
    bare or `mcp__recon-report__`-prefixed, and asserts each one's argument
    list carries `run_id`. This covers stage2.py's cross-project routing
    examples, stage3.py's verification pseudocode, and the autopilot_video.py
    contamination-guardrail example.

    Scanning assembled prompt text (rather than source modules) means
    recon_self_model.MCP_CALL_SIGNATURES — verified never rendered into any
    stage prompt, and task 2231's (W5-ξ) domain — cannot be matched here.

    start_report is harness-called (agents never call it themselves) and is
    intentionally excluded, as in TestReconReportGuidanceDrift.
    """

    @pytest.mark.parametrize(
        'prompt_label,prompt_text',
        _ASSEMBLED_PROMPT_CASES,
        ids=[label for label, _ in _ASSEMBLED_PROMPT_CASES],
    )
    def test_every_report_tool_call_example_shows_run_id(self, prompt_label, prompt_text):
        for tool_name in _AGENT_CALLED_REPORT_TOOLS:
            for paren_idx in _iter_call_openers(prompt_text, tool_name):
                args_substr = _extract_call_args_at(prompt_text, paren_idx)
                assert 'run_id' in args_substr, (
                    f'{prompt_label}: a `{tool_name}(...)` call example is missing '
                    f'`run_id` — got: {tool_name}({args_substr})'
                )


class TestReconReportGuidanceFallback:
    """get_recon_report_tool_guidance()'s exception/fallback branch (reviewer finding).

    _frozen_recon_report_tool_guidance() exists specifically as a run_id-safe
    safety net for when render_recon_report_tool_guidance() raises (e.g. a
    FastMCP internals change). It was originally hand-written prose, never
    exercised by a test nor scanned for the very run_id-omission drift this
    task set out to eliminate — this class covers both gaps. (It is now
    generated rather than hand-written, and lazily rather than at import
    time — see TestFallbackIsDerivedFromTheSameRenderer and the function's own
    docstring — but the tests below still guard the fallback BRANCH's
    behaviour: that it is served on failure, logged, self-heals, and carries
    run_id.)
    """

    def setup_method(self):
        # get_recon_report_tool_guidance() is backed by the lru_cache'd
        # _cached_recon_report_tool_guidance() helper — clear it so tests
        # don't observe each other's cached renders.
        prompts_module._cached_recon_report_tool_guidance.cache_clear()

    def teardown_method(self):
        prompts_module._cached_recon_report_tool_guidance.cache_clear()

    def test_falls_back_and_logs_when_render_raises(self, monkeypatch, caplog):
        """A raising get_recon_report_tool_signatures() forces the frozen fallback."""

        def _raise():
            raise RuntimeError('FastMCP tool-manager internals changed shape')

        monkeypatch.setattr(
            'fused_memory.server.recon_report.get_recon_report_tool_signatures', _raise
        )
        with caplog.at_level(logging.ERROR):
            result = get_recon_report_tool_guidance()

        assert result == _frozen_recon_report_tool_guidance()
        error_records = [r for r in caplog.records if r.levelno == logging.ERROR]
        assert any('falling back' in r.message for r in error_records), (
            f'Expected an ERROR log containing "falling back", got: '
            f'{[r.message for r in error_records]}'
        )

    def test_self_heals_on_next_call_after_transient_failure(self, monkeypatch, caplog):
        """A transient failure must not be cached — the next call retries live.

        Regression guard for the reviewer's robustness finding: because the
        fallback path is deliberately NOT memoized (only a successful render
        is, via _cached_recon_report_tool_guidance), a call made after the
        introspection failure clears should get the real generated guidance
        again in the SAME process, not the fallback forever.

        The self-heal property is proven DIRECTLY (reviewer test-quality
        finding): the healed call is shown to re-invoke
        get_recon_report_tool_signatures itself, via a counting spy wrapped
        around the real function, rather than only indirectly via the
        absence of a "falling back" ERROR log. Log-absence alone is a fragile
        discriminator — it silently stops discriminating if the module
        logger is ever given `propagate=False`, if the log message wording
        changes, or if a caplog level/handler change hides the record — so it
        is kept here only as a secondary signal, not the proof. Text equality
        (`healed == _frozen_recon_report_tool_guidance()`) is not usable as a
        discriminator at all: the fallback is derived from a frozen signature
        snapshot through the same renderer as the live guidance, so the two
        strings are byte-identical whenever the snapshot is in sync with the
        live signatures — the intended steady state, not a bug — which makes
        that comparison true on both branches. Do not restore it as the
        discriminator.
        """

        def _raise():
            raise RuntimeError('transient hiccup')

        monkeypatch.setattr(
            'fused_memory.server.recon_report.get_recon_report_tool_signatures', _raise
        )
        assert get_recon_report_tool_guidance() == _frozen_recon_report_tool_guidance()

        monkeypatch.undo()

        # Wrap the REAL function (the module-level import above, never touched
        # by monkeypatching fused_memory.server.recon_report's attribute) in a
        # counting spy so the healed call's re-invocation of live introspection
        # is an observed fact, not an inference from a log line or a string
        # comparison that can no longer distinguish the two code paths.
        real_get_signatures = get_recon_report_tool_signatures
        call_count = 0

        def _counting_get_signatures():
            nonlocal call_count
            call_count += 1
            return real_get_signatures()

        monkeypatch.setattr(
            'fused_memory.server.recon_report.get_recon_report_tool_signatures',
            _counting_get_signatures,
        )
        caplog.clear()
        with caplog.at_level(logging.ERROR):
            healed = get_recon_report_tool_guidance()

        assert call_count == 1, (
            'healed call must re-invoke live introspection exactly once — got '
            f'{call_count} call(s) to get_recon_report_tool_signatures'
        )
        assert healed == render_recon_report_tool_guidance()
        fallback_error_records = [
            r
            for r in caplog.records
            if r.levelno == logging.ERROR and 'falling back' in r.message
        ]
        assert not fallback_error_records, (
            'healed call must not have taken the fallback branch (expected no '
            f'"falling back" ERROR log), but got: '
            f'{[r.message for r in fallback_error_records]}'
        )

    def test_fallback_call_examples_all_carry_run_id(self):
        """Guard the frozen fallback string with the same run_id scan used above.

        The fallback is now generated (not hand-written) and is verified
        against the live signatures elsewhere (see
        TestFallbackIsDerivedFromTheSameRenderer) — this scan is retained as
        a cheap belt-and-braces guard on the original task-2559 bug, not as
        the mechanism that now prevents drift.
        """
        fallback = _frozen_recon_report_tool_guidance()
        for tool_name in _AGENT_CALLED_REPORT_TOOLS:
            for paren_idx in _iter_call_openers(fallback, tool_name):
                args_substr = _extract_call_args_at(fallback, paren_idx)
                assert 'run_id' in args_substr, (
                    f'fallback: a `{tool_name}(...)` call example is missing '
                    f'`run_id` — got: {tool_name}({args_substr})'
                )


class TestFallbackIsDerivedFromTheSameRenderer:
    """The fallback is rendered from a frozen signature snapshot, not hand-written prose.

    _frozen_recon_report_tool_guidance() is no longer a second, hand-transcribed
    copy of the guidance prose: it is rendered lazily (on first use — reviewer
    robustness finding, see its docstring) from
    _FROZEN_RECON_REPORT_SIGNATURE_SPECS through the *same* template and
    render_call() as the live guidance (render_recon_report_tool_guidance()), so
    the two cannot drift apart in WORDING — there is only one prose template and
    one renderer. The only surface that can still go stale is the snapshot's
    parameter data (names, order, required-ness, and — per the reviewer's
    test-coverage finding — tool-set coverage in BOTH directions); the two
    tests below pin that directly, comparing data structures rather than
    scanning rendered prose.
    """

    def test_fallback_equals_live_generated_guidance(self):
        assert render_recon_report_tool_guidance() == _frozen_recon_report_tool_guidance(), (
            'The frozen fallback no longer matches the live-generated guidance — '
            'update _FROZEN_RECON_REPORT_SIGNATURE_SPECS in '
            'reconciliation/prompts/__init__.py to match the live tool signatures.'
        )

    def test_frozen_snapshot_matches_live_signatures(self):
        """Diagnostic partner to the test above: a precise dict diff, not a multi-KB string diff.

        Also guards the drift check itself against being one-directional
        (reviewer test-coverage finding): comparing only the tools already
        present in _FROZEN_RECON_REPORT_SIGNATURE_SPECS can never notice a
        NEW agent-called tool the snapshot doesn't know about yet — it would
        silently get no rendered guidance — and a renamed/removed live tool
        would otherwise surface as a bare `KeyError` below instead of an
        actionable message. The key-set assertions catch both before the
        per-tool value comparison runs.
        """
        sigs = get_recon_report_tool_signatures()

        assert set(_FROZEN_RECON_REPORT_SIGNATURE_SPECS) == set(_AGENT_CALLED_REPORT_TOOLS), (
            'The frozen snapshot and _AGENT_CALLED_REPORT_TOOLS have diverged — '
            'update _FROZEN_RECON_REPORT_SIGNATURE_SPECS in '
            'reconciliation/prompts/__init__.py and/or _AGENT_CALLED_REPORT_TOOLS '
            'above to match.'
        )
        assert set(_AGENT_CALLED_REPORT_TOOLS) <= set(sigs), (
            'A tool in _AGENT_CALLED_REPORT_TOOLS is no longer registered on the live '
            'recon_report server — update _AGENT_CALLED_REPORT_TOOLS above and '
            '_FROZEN_RECON_REPORT_SIGNATURE_SPECS in reconciliation/prompts/__init__.py.'
        )
        # start_report is harness-called; delete_finding and
        # write_entity_standing_decision are registered on the live server but
        # are never rendered by render_recon_report_tool_guidance() either (see
        # plan.json's design decision on tool scope — verified empirically
        # against get_recon_report_tool_signatures() at amendment time: these
        # 3 plus the 9 in _AGENT_CALLED_REPORT_TOOLS are the complete live set).
        # Any OTHER live tool is therefore a newly-registered agent-called tool
        # the guidance would silently omit.
        not_agent_guidance_tools = {
            'start_report',
            'delete_finding',
            'write_entity_standing_decision',
        }
        undeclared = set(sigs) - not_agent_guidance_tools - set(_AGENT_CALLED_REPORT_TOOLS)
        assert not undeclared, (
            f'The live recon_report server has tool(s) {undeclared} not covered by '
            '_AGENT_CALLED_REPORT_TOOLS and not in the known non-agent-guidance set '
            f'{not_agent_guidance_tools} — a newly registered agent-called tool would '
            'get no rendered guidance. Add it to _AGENT_CALLED_REPORT_TOOLS above and '
            'to _FROZEN_RECON_REPORT_SIGNATURE_SPECS and the render_call(...) list in '
            'reconciliation/prompts/__init__.py.'
        )

        live = {
            tool: tuple(
                (name, param.default is inspect.Parameter.empty)
                for name, param in sigs[tool].parameters.items()
            )
            for tool in _FROZEN_RECON_REPORT_SIGNATURE_SPECS
        }
        assert live == dict(_FROZEN_RECON_REPORT_SIGNATURE_SPECS), (
            'The frozen signature snapshot has drifted from the live tool '
            'signatures (a name, param order, or required-ness differs) — update '
            '_FROZEN_RECON_REPORT_SIGNATURE_SPECS in reconciliation/prompts/__init__.py '
            'to match.'
        )
