"""Drift-guard tests for _RECON_REPORT_TOOL_GUIDANCE (task-2559).

_RECON_REPORT_TOOL_GUIDANCE (reconciliation/prompts/__init__.py) is generated
from live recon_report FastMCP tool signatures via
render_recon_report_tool_guidance() rather than hand-transcribed, because
hand-maintenance drifted twice — most recently, every example omitted the
required `run_id` kwarg, undetected across a full reviewer round.

This module asserts:
- every report-tool call example in the fully ASSEMBLED stage prompts
  (bare inline examples included, not just the generated guidance block)
  shows `run_id` — this is the only way to catch hand-written inline
  examples like stage2.py's cross-project routing snippets or stage3.py's
  verification pseudocode, which render_recon_report_tool_guidance() never
  touches.
- _frozen_recon_report_tool_guidance() — rendered lazily (reviewer robustness
  finding: NOT at module-import time, so a bad snapshot edit cannot become an
  ImportError for every consumer of the `prompts` package) from
  _FROZEN_RECON_REPORT_SIGNATURE_SPECS through the same template and
  render_call() as the live guidance — equals render_recon_report_tool_guidance(),
  and the frozen signature snapshot matches the live tool signatures (name,
  order, required-ness, and tool-set coverage in both directions). See
  TestFallbackIsDerivedFromTheSameRenderer.

A minimal smoke test also confirms render_recon_report_tool_guidance() runs
cleanly and produces non-empty text. For that GENERATED path specifically,
the module deliberately does not re-introspect live signatures or pin
call-shape substrings on its output: those would be tautological, since the
shipped guidance is generated by iterating the exact same live signatures
such a test would re-check, so the assertions could not fail short of import
already having fallen back. TestFallbackIsDerivedFromTheSameRenderer is
different in kind, not degree: it compares two RENDERS FROM DIFFERENT
SIGNATURE SOURCES — the frozen snapshot vs. live introspection — rather than
re-checking generated text against the signatures that generated it, so it
can genuinely fail when the snapshot drifts.

TestReconReportGuidanceFallback's test_fallback_call_examples_all_carry_run_id
run_id scan is now satisfied by construction (the fallback is generated, and
run_id is required in the snapshot for every tool) — it is retained as a
cheap belt-and-braces guard on the original task-2559 bug, not as the
mechanism that now prevents drift; do not mistake it for one.

Task 3878 widened the guard from "does each LISTED tool carry run_id" to
"does every REGISTERED tool reach the agent at all", after finding two tools
that had drifted past the old check: delete_finding (callable in every stage,
in no rendered guidance) and write_entity_standing_decision (registered, in no
server-level listing). Four things changed here:

- There is NO hand-maintained tool-name list left in this module.
  _SHARED_GUIDANCE_REPORT_TOOLS is DERIVED at import from the live tool set
  minus HARNESS_CALLED_REPORT_TOOLS and STAGE_GATED_REPORT_TOOLS, which live
  next to the @mcp.tool() registrations. The list this replaced was stale, and
  it lived in a test file the tool author never opens — the drift itself.
- That three-way classification (shared-guidance / harness-called /
  stage-gated) is pinned to the REAL enforcement surface: it is cross-checked
  against DISALLOW_RECON_REPORT_LEDGER_WRITES in cli_stage_runner.py, so it
  cannot become a second hand-maintained list that drifts from the actual gate.
- Coverage is asserted on BOTH surfaces a tool can reach an agent through:
  RECON_REPORT_INSTRUCTIONS (the stage-agnostic server-level listing, for ALL
  registered tools) and the rendered guidance block (for shared-guidance tools).
  The RECON_REPORT_INSTRUCTIONS half is FULLY independent of the renderer —
  those instructions are hand-written prose that is never generated.
- TestRendererCoversEverySignatureItIsGiven is the assertion that escapes the
  tautology described above: it injects a SYNTHETIC tool the renderer has never
  heard of straight into _render_recon_report_tool_guidance()'s only argument,
  proving "never silently omit a tool I was handed" from a signature source the
  renderer cannot have hard-coded. The derived-coverage tests re-read the same
  live signatures the renderer generates from, so they catch a filtering,
  lookup or placement bug but not a signature-source bug.

start_report gets a PROSE mention in the guidance but no call shape, and the
stage-gated tools get neither. That is not a property of the renderer, which
renders every key it is handed: render_recon_report_tool_guidance() filters the
live tool set before calling it — see reconciliation/prompts/__init__.py. Both
omissions are asserted positively here (TestNonSharedToolsAreNotAdvertisedToEveryStage),
because --disallowed-tools OMITS a denied tool rather than rejecting the call,
so advertising one to a stage that cannot call it produces silence, not a
refusal the agent could act on.
"""
from __future__ import annotations

import inspect
import logging
import re

import pytest

from fused_memory.reconciliation import prompts as prompts_module
from fused_memory.reconciliation.prompts import (
    _FROZEN_RECON_REPORT_SIGNATURE_SPECS,
    _frozen_recon_report_tool_guidance,
    get_recon_report_tool_guidance,
    render_recon_report_tool_guidance,
)
from fused_memory.reconciliation.prompts.stage1 import STAGE1_SYSTEM_PROMPT
from fused_memory.reconciliation.prompts.stage2 import (
    STAGE2_SYSTEM_PROMPT,
    build_stage2_system_prompt,
)
from fused_memory.reconciliation.prompts.stage3 import STAGE3_SYSTEM_PROMPT
from fused_memory.server.recon_report import (
    HARNESS_CALLED_REPORT_TOOLS,
    RECON_REPORT_INSTRUCTIONS,
    STAGE_GATED_REPORT_TOOLS,
    get_recon_report_tool_signatures,
)


def _live_report_tool_names() -> tuple[str, ...]:
    """Every tool NAME registered on the live recon_report server, in registration order.

    Module-level helper (rather than a fixture) so it can drive
    ``@pytest.mark.parametrize``: pytest then reports one test id per tool,
    e.g. ``[write_entity_standing_decision]``, instead of collapsing every
    undocumented tool into a single aggregate failure that names only the
    first one it hits.
    """
    return tuple(get_recon_report_tool_signatures())


_LIVE_REPORT_TOOL_NAMES = _live_report_tool_names()

# The SHARED-GUIDANCE report tools: every live-registered tool that is neither
# harness-called nor stage-gated. DERIVED from the live tool set and the
# classification constants that sit next to the @mcp.tool() registrations — NOT
# hand-maintained here (task 3878). The hand-written tuple this replaces went
# stale against the live server (it never gained delete_finding), and it lived
# in a test file the tool author never opens, which is the drift this task
# exists to close. There is deliberately no hand-maintained tool-NAME list left
# in this module: a newly registered tool joins this tuple automatically and is
# then held to every assertion below.
_SHARED_GUIDANCE_REPORT_TOOLS = tuple(
    name
    for name in _LIVE_REPORT_TOOL_NAMES
    if name not in HARNESS_CALLED_REPORT_TOOLS and name not in STAGE_GATED_REPORT_TOOLS
)

# Backwards-compatible alias: the run_id scans below read as "every tool an
# agent is told to call", which is exactly the shared-guidance set.
_AGENT_CALLED_REPORT_TOOLS = _SHARED_GUIDANCE_REPORT_TOOLS


def _iter_call_openers(text: str, tool_name: str):
    """Yield the index of the opening '(' for every *tool_name* call in *text*.

    Matches both the bare form (``tool_name(``) and the
    ``mcp__recon-report__``-prefixed form (``mcp__recon-report__tool_name(``),
    as long as the call opener is not itself embedded inside a longer
    identifier — i.e. the character immediately before the match (before
    the prefix, if present, otherwise before the bare name) must not be an
    identifier character.
    """
    pattern = re.compile(r'(?<![A-Za-z0-9_])(?:mcp__recon-report__)?' + re.escape(tool_name) + r'\(')
    for m in pattern.finditer(text):
        yield m.end() - 1


def _extract_call_args_at(text: str, paren_idx: int) -> str:
    """Return the balanced-paren argument substring starting at *paren_idx* ('(')."""
    assert text[paren_idx] == '('
    depth = 0
    for i in range(paren_idx, len(text)):
        if text[i] == '(':
            depth += 1
        elif text[i] == ')':
            depth -= 1
            if depth == 0:
                return text[paren_idx + 1 : i]
    raise AssertionError(f'Unbalanced parens scanning from index {paren_idx}')


class TestReconReportGuidanceDrift:
    """render_recon_report_tool_guidance() runs cleanly and produces real guidance."""

    def test_render_returns_non_empty_string(self):
        """Smoke test: rendering the guidance succeeds and yields non-empty text.

        Deliberately does not re-introspect live signatures or pin call-shape
        substrings — the shipped guidance is generated by iterating the exact
        same live signatures such assertions would re-check, so they would be
        tautological (unable to fail short of import already having fallen
        back).
        """
        result = render_recon_report_tool_guidance()
        assert isinstance(result, str)
        assert result


class TestEveryRegisteredToolIsDocumented:
    """Every live-registered recon-report tool is named in RECON_REPORT_INSTRUCTIONS.

    RECON_REPORT_INSTRUCTIONS is the SERVER-level listing FastMCP hands to any
    MCP client on connect — it is stage-agnostic, so it is the one surface that
    must cover ALL registered tools regardless of which stage may call them.
    Unlike the generated guidance block, it is hand-written prose that is never
    generated from the signatures, which makes this assertion fully independent
    of the renderer (contrast the candour in this module's docstring about the
    generated path's tautological assertions).
    """

    @pytest.mark.parametrize(
        'tool_name', _LIVE_REPORT_TOOL_NAMES, ids=list(_LIVE_REPORT_TOOL_NAMES)
    )
    def test_tool_is_named_in_server_instructions(self, tool_name):
        assert tool_name in RECON_REPORT_INSTRUCTIONS, (
            f'The tool `{tool_name}` is registered on the live recon_report server but '
            'is not named anywhere in RECON_REPORT_INSTRUCTIONS '
            '(server/recon_report.py) — a registered tool absent from '
            'RECON_REPORT_INSTRUCTIONS is invisible to any MCP client that reads the '
            'server instructions — add it there.'
        )


class TestReportToolClassificationPartitionsTheLiveToolSet:
    """HARNESS_CALLED / STAGE_GATED / (the rest = shared guidance) partition the live tools.

    Every registered recon-report tool belongs to exactly one of three buckets:

    - **harness-called** — the harness calls it for the agent (``start_report``);
      it must never be rendered as a call example.
    - **stage-gated** — held by some stages but denied in others, so it must not
      appear in the STAGE-AGNOSTIC guidance block that is interpolated into all
      three stage prompts.
    - **shared guidance** — everything else, i.e. the derived remainder.

    The remainder is DERIVED rather than declared, which is what makes the split
    a genuine partition with no unclassified leftovers by construction: a
    newly-registered tool lands in shared guidance automatically and is rendered,
    rather than being silently dropped for want of a hand-maintained entry.
    """

    def test_classified_tools_are_all_still_registered(self):
        sigs = set(get_recon_report_tool_signatures())
        stale = (HARNESS_CALLED_REPORT_TOOLS | STAGE_GATED_REPORT_TOOLS) - sigs
        assert not stale, (
            f'Classified tool(s) {stale} are no longer registered on the live recon_report '
            'server — remove them from HARNESS_CALLED_REPORT_TOOLS / '
            'STAGE_GATED_REPORT_TOOLS in server/recon_report.py.'
        )

    def test_the_two_declared_buckets_are_disjoint(self):
        overlap = HARNESS_CALLED_REPORT_TOOLS & STAGE_GATED_REPORT_TOOLS
        assert not overlap, (
            f'Tool(s) {overlap} are classified as BOTH harness-called and stage-gated — '
            'each registered tool must be classified into exactly one of '
            '{shared guidance, harness-called, stage-gated}.'
        )

    def test_harness_called_is_exactly_start_report(self):
        assert set(HARNESS_CALLED_REPORT_TOOLS) == {'start_report'}, (
            'start_report is the only tool the harness calls on the agent\'s behalf. If '
            'another tool became harness-called, the guidance block and the stage prompts '
            'both need reviewing — this is not a mechanical addition.'
        )

    def test_shared_guidance_remainder_is_non_empty(self):
        sigs = set(get_recon_report_tool_signatures())
        shared = sigs - HARNESS_CALLED_REPORT_TOOLS - STAGE_GATED_REPORT_TOOLS
        assert shared, (
            'Every live recon-report tool is classified as harness-called or stage-gated, '
            'leaving no shared-guidance tools at all — the guidance block would be empty. '
            'Classify each registered tool into exactly one of {shared guidance, '
            'harness-called, stage-gated}.'
        )

    def test_stage_gated_matches_the_real_enforcement_surface(self):
        """Cross-check the classification against the list that actually gates the stages.

        This is the one assertion here that compares two genuinely INDEPENDENT
        sources of truth. DISALLOW_RECON_REPORT_LEDGER_WRITES is what the stage
        runner actually passes to ``--disallowed-tools``; without this check
        STAGE_GATED_REPORT_TOOLS would just be a third hand-maintained list,
        vulnerable to exactly the drift this task exists to fix. Pinning them
        together means gating a tool without classifying it (or classifying it
        without gating it) fails loudly here.
        """
        from fused_memory.reconciliation.cli_stage_runner import (
            DISALLOW_RECON_REPORT_LEDGER_WRITES,
        )

        gated = {
            name.removeprefix('mcp__recon-report__')
            for name in DISALLOW_RECON_REPORT_LEDGER_WRITES
        }
        assert set(STAGE_GATED_REPORT_TOOLS) == gated, (
            'STAGE_GATED_REPORT_TOOLS (server/recon_report.py) and '
            'DISALLOW_RECON_REPORT_LEDGER_WRITES (reconciliation/cli_stage_runner.py) '
            f'disagree: classified={set(STAGE_GATED_REPORT_TOOLS)}, actually gated={gated}. '
            'A recon-report tool that is denied in some stages must be classified '
            'stage-gated so it stays out of the stage-agnostic guidance block, and a tool '
            'classified stage-gated must actually be gated. Classify each registered tool '
            'into exactly one of {shared guidance, harness-called, stage-gated}.'
        )


class TestSharedGuidanceToolsAreAllRendered:
    """Every derived shared-guidance tool actually appears in the shipped guidance.

    CANDOUR (mirrors this module's docstring): this is only PARTIALLY
    independent. render_recon_report_tool_guidance() derives from the same live
    signatures the assertions below re-read, so it catches a filtering, lookup,
    or placement bug but NOT a signature-source bug.
    TestRendererCoversEverySignatureItIsGiven is the assertion that is
    independent in KIND — do not mistake this one for the guard with teeth.
    """

    @pytest.mark.parametrize(
        'tool_name', _SHARED_GUIDANCE_REPORT_TOOLS, ids=list(_SHARED_GUIDANCE_REPORT_TOOLS)
    )
    def test_shared_guidance_tool_is_rendered_as_a_call_example(self, tool_name):
        guidance = render_recon_report_tool_guidance()
        assert list(_iter_call_openers(guidance, tool_name)), (
            f'`{tool_name}` is a shared-guidance tool (registered, and neither '
            'harness-called nor stage-gated) but no call example for it appears in '
            'render_recon_report_tool_guidance()\'s output — the agent is never told it '
            'exists. Either render it, or classify it in HARNESS_CALLED_REPORT_TOOLS / '
            'STAGE_GATED_REPORT_TOOLS (server/recon_report.py) if it genuinely should '
            'not be advertised to every stage.'
        )

    @pytest.mark.parametrize(
        'tool_name', _SHARED_GUIDANCE_REPORT_TOOLS, ids=list(_SHARED_GUIDANCE_REPORT_TOOLS)
    )
    def test_shared_guidance_tool_takes_run_id_first(self, tool_name):
        """Pin the premise the run_id scans silently depend on.

        The assembled-prompt and fallback scans assert every report-tool call
        example carries `run_id`. That check is only meaningful while every
        shared-guidance tool is actually run-scoped. A future shared-guidance
        tool that takes no run_id (write_entity_standing_decision is the
        existing precedent — which is why it is stage-gated, not shared) would
        make those scans quietly vacuous for it. Fail here, with an actionable
        message, rather than letting the guard erode in silence.
        """
        params = list(get_recon_report_tool_signatures()[tool_name].parameters)
        assert params[:1] == ['run_id'], (
            f'`{tool_name}` is a shared-guidance tool but its first parameter is '
            f'{params[:1] or ["<none>"]}, not run_id. The run_id scans in this module '
            'assume every shared-guidance tool is run-scoped; a tool that is not needs '
            'either its own classification or an explicit carve-out here.'
        )


class TestNonSharedToolsAreNotAdvertisedToEveryStage:
    """Harness-called and stage-gated tools must not be rendered as call examples.

    The mirror image of TestSharedGuidanceToolsAreAllRendered, and the same
    shape as test_recon_amend_tool_advertisement.py::test_absent_from_stage3_prompt.
    `--disallowed-tools` OMITS a denied tool rather than rejecting the call
    (cli_stage_runner.py), so advertising a denied tool in the stage-agnostic
    block does not produce a clean refusal — it tells a stage about an action it
    cannot take, and for write_entity_standing_decision specifically it would
    license a durable SQLite-ledger write from stages that are read-only with
    respect to the ledger.
    """

    def test_start_report_has_no_call_example(self):
        """start_report's PROSE mention must survive; only its call example must not exist.

        Asserted via the call-opener scan rather than the bare name, because
        the guidance deliberately says "The harness calls
        `mcp__recon-report__start_report` for you" — that sentence is the whole
        reason the agent knows not to call it.
        """
        guidance = render_recon_report_tool_guidance()
        assert 'mcp__recon-report__start_report' in guidance, (
            'the prose mention telling the agent the harness calls start_report for it '
            'has been lost — that sentence is what stops the agent calling it itself'
        )
        assert not list(_iter_call_openers(guidance, 'start_report')), (
            'render_recon_report_tool_guidance() emits a start_report(...) CALL EXAMPLE. '
            'start_report is harness-called — the harness opens the report before the '
            'stage begins, so an example invites a redundant call. Keep the prose '
            'mention, drop the call shape.'
        )

    @pytest.mark.parametrize('tool_name', sorted(STAGE_GATED_REPORT_TOOLS))
    def test_stage_gated_tool_is_absent_from_shared_guidance(self, tool_name):
        guidance = render_recon_report_tool_guidance()
        assert tool_name not in guidance, (
            f'`{tool_name}` is stage-gated (denied in some stages via '
            'DISALLOW_RECON_REPORT_LEDGER_WRITES) but appears in the STAGE-AGNOSTIC '
            'guidance block, which is interpolated into all three stage prompts — so '
            'Stage 1 and Stage 3 are being told about an action they cannot take.'
        )

    @pytest.mark.parametrize(
        'prompt_label,prompt_text',
        [
            ('STAGE1_SYSTEM_PROMPT', STAGE1_SYSTEM_PROMPT),
            ('STAGE3_SYSTEM_PROMPT', STAGE3_SYSTEM_PROMPT),
        ],
    )
    def test_stage_gated_tools_absent_from_denying_stage_prompts(self, prompt_label, prompt_text):
        """The end-to-end version: scan the ASSEMBLED prompts of the stages that deny it."""
        for tool_name in sorted(STAGE_GATED_REPORT_TOOLS):
            assert tool_name not in prompt_text, (
                f'{prompt_label} names `{tool_name}`, but that stage DENIES it via '
                'DISALLOW_RECON_REPORT_LEDGER_WRITES (cli_stage_runner.py). Naming a '
                'denied tool in a stage prompt tells the agent about an action it cannot '
                'take, and the denial surfaces as a silently missing tool rather than an '
                'explanation.'
            )


class TestRendererCoversEverySignatureItIsGiven:
    """_render_recon_report_tool_guidance() renders EVERY tool in the mapping it is handed.

    This is the load-bearing, NON-TAUTOLOGICAL assertion of task 3878. The
    renderer's only argument is already a plain
    ``{tool: ((param, required), ...)}`` mapping (deliberately not
    ``inspect.Signature`` objects), which makes it a dependency-injection seam:
    a synthetic tool the renderer has never heard of can be injected with no
    monkeypatching and no fake FastMCP server. Because that tool is NOT
    registered anywhere, the renderer cannot have hard-coded it — so this
    proves the actual new property ("never silently omit a tool I was handed")
    from a signature source independent of the renderer, unlike the
    derived-coverage tests elsewhere in this module which re-read the same live
    signatures the renderer generates from.
    """

    # A tool the renderer has never heard of. `commit_sha` deliberately has no
    # entry in _RECON_REPORT_PLACEHOLDERS, so it also exercises the generic
    # <param_name> fallback.
    SYNTHETIC_TOOL = 'cite_commit'
    SYNTHETIC_SPEC = (('run_id', True), ('finding_id', True), ('commit_sha', True))

    def _render_with_synthetic_tool(self) -> str:
        signatures = dict(_FROZEN_RECON_REPORT_SIGNATURE_SPECS)
        signatures[self.SYNTHETIC_TOOL] = self.SYNTHETIC_SPEC
        return prompts_module._render_recon_report_tool_guidance(signatures)

    def test_unknown_tool_is_rendered_as_a_call_example(self):
        rendered = self._render_with_synthetic_tool()
        assert f'mcp__recon-report__{self.SYNTHETIC_TOOL}(' in rendered, (
            f'_render_recon_report_tool_guidance() silently omitted `{self.SYNTHETIC_TOOL}` '
            'from its output even though it was handed that tool\'s signature — the '
            'renderer must render every key of the mapping it is given, so a '
            'newly-registered tool can never be silently absent from the guidance.'
        )

    def test_unknown_tool_renders_all_of_its_parameters(self):
        rendered = self._render_with_synthetic_tool()
        openers = list(_iter_call_openers(rendered, self.SYNTHETIC_TOOL))
        assert openers, f'no `{self.SYNTHETIC_TOOL}(` call example found in the rendered guidance'
        args_substr = _extract_call_args_at(rendered, openers[0])
        for param_name, _required in self.SYNTHETIC_SPEC:
            assert param_name in args_substr, (
                f'the rendered `{self.SYNTHETIC_TOOL}(...)` example is missing the '
                f'`{param_name}` parameter — got: {self.SYNTHETIC_TOOL}({args_substr})'
            )

    def test_known_tools_still_render_when_an_unknown_one_is_present(self):
        """An unrecognised tool must be ADDITIVE, never displace the curated prose."""
        rendered = self._render_with_synthetic_tool()
        for tool_name in _FROZEN_RECON_REPORT_SIGNATURE_SPECS:
            assert f'mcp__recon-report__{tool_name}(' in rendered, (
                f'rendering with an unrecognised tool present dropped the curated '
                f'`{tool_name}` call example'
            )


# Fully assembled stage-prompt texts to scan for inline report-tool call examples.
# build_stage2_system_prompt('autopilot_video') is included because it injects
# AUTOPILOT_VIDEO_CONTAMINATION_GUARDRAIL, which carries its own cross-project
# add_finding example only present under that project_id — the plain
# STAGE2_SYSTEM_PROMPT / build_stage2_system_prompt('dark_factory') texts never
# surface it.
_ASSEMBLED_PROMPT_CASES = (
    ('STAGE1_SYSTEM_PROMPT', STAGE1_SYSTEM_PROMPT),
    ('STAGE2_SYSTEM_PROMPT', STAGE2_SYSTEM_PROMPT),
    ('STAGE3_SYSTEM_PROMPT', STAGE3_SYSTEM_PROMPT),
    ("build_stage2_system_prompt('dark_factory')", build_stage2_system_prompt('dark_factory')),
    ("build_stage2_system_prompt('autopilot_video')", build_stage2_system_prompt('autopilot_video')),
)


class TestReconReportRunIdGuardOverAssembledPrompts:
    """Every report-tool call example in the ASSEMBLED stage prompts shows run_id.

    render_recon_report_tool_guidance() (see TestReconReportGuidanceDrift above)
    only generates the shared guidance block — it cannot reach hand-written
    inline examples elsewhere in a stage prompt. This class scans the fully
    assembled prompt TEXT (not source files) for every report-tool call opener,
    bare or `mcp__recon-report__`-prefixed, and asserts each one's argument
    list carries `run_id`. This covers stage2.py's cross-project routing
    examples, stage3.py's verification pseudocode, and the autopilot_video.py
    contamination-guardrail example.

    Scanning assembled prompt text (rather than source modules) means
    recon_self_model.MCP_CALL_SIGNATURES — verified never rendered into any
    stage prompt, and task 2231's (W5-ξ) domain — cannot be matched here.

    Scans the SHARED-GUIDANCE tools (_SHARED_GUIDANCE_REPORT_TOOLS, derived
    above): start_report is harness-called and the stage-gated tools are denied
    in some stages, so neither should appear as a call example in an assembled
    prompt at all — that is asserted separately, and positively, by
    TestNonSharedToolsAreNotAdvertisedToEveryStage. This scan's premise (every
    shared-guidance tool is run-scoped, so "no run_id" really is a bug rather
    than a tool that simply has no run_id) is pinned by
    TestSharedGuidanceToolsAreAllRendered.test_shared_guidance_tool_takes_run_id_first.
    """

    @pytest.mark.parametrize(
        'prompt_label,prompt_text',
        _ASSEMBLED_PROMPT_CASES,
        ids=[label for label, _ in _ASSEMBLED_PROMPT_CASES],
    )
    def test_every_report_tool_call_example_shows_run_id(self, prompt_label, prompt_text):
        for tool_name in _AGENT_CALLED_REPORT_TOOLS:
            for paren_idx in _iter_call_openers(prompt_text, tool_name):
                args_substr = _extract_call_args_at(prompt_text, paren_idx)
                assert 'run_id' in args_substr, (
                    f'{prompt_label}: a `{tool_name}(...)` call example is missing '
                    f'`run_id` — got: {tool_name}({args_substr})'
                )


class TestReconReportGuidanceFallback:
    """get_recon_report_tool_guidance()'s exception/fallback branch (reviewer finding).

    _frozen_recon_report_tool_guidance() exists specifically as a run_id-safe
    safety net for when render_recon_report_tool_guidance() raises (e.g. a
    FastMCP internals change). It was originally hand-written prose, never
    exercised by a test nor scanned for the very run_id-omission drift this
    task set out to eliminate — this class covers both gaps. (It is now
    generated rather than hand-written, and lazily rather than at import
    time — see TestFallbackIsDerivedFromTheSameRenderer and the function's own
    docstring — but the tests below still guard the fallback BRANCH's
    behaviour: that it is served on failure, logged, self-heals, and carries
    run_id.)
    """

    def setup_method(self):
        # get_recon_report_tool_guidance() is backed by the lru_cache'd
        # _cached_recon_report_tool_guidance() helper — clear it so tests
        # don't observe each other's cached renders.
        prompts_module._cached_recon_report_tool_guidance.cache_clear()

    def teardown_method(self):
        prompts_module._cached_recon_report_tool_guidance.cache_clear()

    def test_falls_back_and_logs_when_render_raises(self, monkeypatch, caplog):
        """A raising get_recon_report_tool_signatures() forces the frozen fallback."""

        def _raise():
            raise RuntimeError('FastMCP tool-manager internals changed shape')

        monkeypatch.setattr(
            'fused_memory.server.recon_report.get_recon_report_tool_signatures', _raise
        )
        with caplog.at_level(logging.ERROR):
            result = get_recon_report_tool_guidance()

        assert result == _frozen_recon_report_tool_guidance()
        error_records = [r for r in caplog.records if r.levelno == logging.ERROR]
        assert any('falling back' in r.message for r in error_records), (
            f'Expected an ERROR log containing "falling back", got: '
            f'{[r.message for r in error_records]}'
        )

    def test_self_heals_on_next_call_after_transient_failure(self, monkeypatch, caplog):
        """A transient failure must not be cached — the next call retries live.

        Regression guard for the reviewer's robustness finding: because the
        fallback path is deliberately NOT memoized (only a successful render
        is, via _cached_recon_report_tool_guidance), a call made after the
        introspection failure clears should get the real generated guidance
        again in the SAME process, not the fallback forever.

        The self-heal property is proven DIRECTLY (reviewer test-quality
        finding): the healed call is shown to re-invoke
        get_recon_report_tool_signatures itself, via a counting spy wrapped
        around the real function, rather than only indirectly via the
        absence of a "falling back" ERROR log. Log-absence alone is a fragile
        discriminator — it silently stops discriminating if the module
        logger is ever given `propagate=False`, if the log message wording
        changes, or if a caplog level/handler change hides the record — so it
        is kept here only as a secondary signal, not the proof. Text equality
        (`healed == _frozen_recon_report_tool_guidance()`) is not usable as a
        discriminator at all: the fallback is derived from a frozen signature
        snapshot through the same renderer as the live guidance, so the two
        strings are byte-identical whenever the snapshot is in sync with the
        live signatures — the intended steady state, not a bug — which makes
        that comparison true on both branches. Do not restore it as the
        discriminator.
        """

        def _raise():
            raise RuntimeError('transient hiccup')

        monkeypatch.setattr(
            'fused_memory.server.recon_report.get_recon_report_tool_signatures', _raise
        )
        assert get_recon_report_tool_guidance() == _frozen_recon_report_tool_guidance()

        monkeypatch.undo()

        # Wrap the REAL function (the module-level import above, never touched
        # by monkeypatching fused_memory.server.recon_report's attribute) in a
        # counting spy so the healed call's re-invocation of live introspection
        # is an observed fact, not an inference from a log line or a string
        # comparison that can no longer distinguish the two code paths.
        real_get_signatures = get_recon_report_tool_signatures
        call_count = 0

        def _counting_get_signatures():
            nonlocal call_count
            call_count += 1
            return real_get_signatures()

        monkeypatch.setattr(
            'fused_memory.server.recon_report.get_recon_report_tool_signatures',
            _counting_get_signatures,
        )
        caplog.clear()
        with caplog.at_level(logging.ERROR):
            healed = get_recon_report_tool_guidance()

        assert call_count == 1, (
            'healed call must re-invoke live introspection exactly once — got '
            f'{call_count} call(s) to get_recon_report_tool_signatures'
        )
        assert healed == render_recon_report_tool_guidance()
        fallback_error_records = [
            r
            for r in caplog.records
            if r.levelno == logging.ERROR and 'falling back' in r.message
        ]
        assert not fallback_error_records, (
            'healed call must not have taken the fallback branch (expected no '
            f'"falling back" ERROR log), but got: '
            f'{[r.message for r in fallback_error_records]}'
        )

    def test_fallback_call_examples_all_carry_run_id(self):
        """Guard the frozen fallback string with the same run_id scan used above.

        The fallback is now generated (not hand-written) and is verified
        against the live signatures elsewhere (see
        TestFallbackIsDerivedFromTheSameRenderer) — this scan is retained as
        a cheap belt-and-braces guard on the original task-2559 bug, not as
        the mechanism that now prevents drift.
        """
        fallback = _frozen_recon_report_tool_guidance()
        for tool_name in _AGENT_CALLED_REPORT_TOOLS:
            for paren_idx in _iter_call_openers(fallback, tool_name):
                args_substr = _extract_call_args_at(fallback, paren_idx)
                assert 'run_id' in args_substr, (
                    f'fallback: a `{tool_name}(...)` call example is missing '
                    f'`run_id` — got: {tool_name}({args_substr})'
                )


class TestFallbackIsDerivedFromTheSameRenderer:
    """The fallback is rendered from a frozen signature snapshot, not hand-written prose.

    _frozen_recon_report_tool_guidance() is no longer a second, hand-transcribed
    copy of the guidance prose: it is rendered lazily (on first use — reviewer
    robustness finding, see its docstring) from
    _FROZEN_RECON_REPORT_SIGNATURE_SPECS through the *same* template and
    render_call() as the live guidance (render_recon_report_tool_guidance()), so
    the two cannot drift apart in WORDING — there is only one prose template and
    one renderer. The only surface that can still go stale is the snapshot's
    parameter data (names, order, required-ness, and — per the reviewer's
    test-coverage finding — tool-set coverage in BOTH directions); the two
    tests below pin that directly, comparing data structures rather than
    scanning rendered prose.
    """

    def test_fallback_equals_live_generated_guidance(self):
        assert render_recon_report_tool_guidance() == _frozen_recon_report_tool_guidance(), (
            'The frozen fallback no longer matches the live-generated guidance — '
            'update _FROZEN_RECON_REPORT_SIGNATURE_SPECS in '
            'reconciliation/prompts/__init__.py to match the live tool signatures.'
        )

    def test_frozen_snapshot_matches_live_signatures(self):
        """Diagnostic partner to the test above: a precise dict diff, not a multi-KB string diff.

        Also guards the drift check itself against being one-directional
        (reviewer test-coverage finding): comparing only the tools already
        present in _FROZEN_RECON_REPORT_SIGNATURE_SPECS can never notice a
        NEW shared-guidance tool the snapshot doesn't know about yet — it
        would silently get no rendered guidance — and a renamed/removed live
        tool would otherwise surface as a bare `KeyError` below instead of an
        actionable message. The key-set assertion catches both before the
        per-tool value comparison runs.

        The snapshot is compared against the DERIVED shared-guidance set
        (task 3878). The previous version of this test subtracted a
        hand-written ``not_agent_guidance_tools`` allowlist that named
        start_report, delete_finding and write_entity_standing_decision — so
        the two tools this task found already drifted were precisely the ones
        that allowlist was muting. With the set derived from the live tool
        names minus the classification constants, the old "undeclared" check
        is empty by construction and has been replaced by the assertion that
        still has teeth: the snapshot must cover exactly the shared-guidance
        set.
        """
        sigs = get_recon_report_tool_signatures()

        assert set(_FROZEN_RECON_REPORT_SIGNATURE_SPECS) == set(_SHARED_GUIDANCE_REPORT_TOOLS), (
            'The frozen snapshot does not cover exactly the shared-guidance tools — '
            'update _FROZEN_RECON_REPORT_SIGNATURE_SPECS in '
            'reconciliation/prompts/__init__.py to match. Missing from the snapshot: '
            f'{set(_SHARED_GUIDANCE_REPORT_TOOLS) - set(_FROZEN_RECON_REPORT_SIGNATURE_SPECS)}; '
            'stale in the snapshot: '
            f'{set(_FROZEN_RECON_REPORT_SIGNATURE_SPECS) - set(_SHARED_GUIDANCE_REPORT_TOOLS)}.'
        )

        live = {
            tool: tuple(
                (name, param.default is inspect.Parameter.empty)
                for name, param in sigs[tool].parameters.items()
            )
            for tool in _FROZEN_RECON_REPORT_SIGNATURE_SPECS
        }
        assert live == dict(_FROZEN_RECON_REPORT_SIGNATURE_SPECS), (
            'The frozen signature snapshot has drifted from the live tool '
            'signatures (a name, param order, or required-ness differs) — update '
            '_FROZEN_RECON_REPORT_SIGNATURE_SPECS in reconciliation/prompts/__init__.py '
            'to match.'
        )


class TestEveryRegisteredToolReachesTheAgentSomehow:
    """The end-to-end contract task 3878 was filed to close, asserted as ONE thing.

    Every registered recon-report tool must be documented on at least the
    surface its classification requires:

    - ALL of them in ``RECON_REPORT_INSTRUCTIONS`` — the stage-agnostic
      server-level listing FastMCP hands any MCP client on connect.
    - every SHARED-GUIDANCE tool additionally in
      ``render_recon_report_tool_guidance()`` — the block interpolated into all
      three stage prompts, which is the only surface a stage agent actually
      reads.

    Both halves are asserted individually elsewhere in this module
    (:class:`TestEveryRegisteredToolIsDocumented` and
    :class:`TestSharedGuidanceToolsAreAllRendered`); they are re-asserted here
    through the same helpers so the two halves read as one contract rather than
    two unrelated guards a future edit can quietly split.

    CANDOUR about what this proves, mirroring this module's docstring:

    - The ``RECON_REPORT_INSTRUCTIONS`` half is FULLY independent. Those
      instructions are hand-written prose that is never generated from the
      signatures, so nothing about the tool set is being compared against
      itself.
    - The guidance half is only PARTIALLY independent.
      ``render_recon_report_tool_guidance()`` derives from the same live
      signatures this test re-reads, so it catches a filtering, lookup, or
      placement bug — the delete_finding regression below was exactly that —
      but it CANNOT catch a signature-source bug, because a tool missing from
      ``get_recon_report_tool_signatures()`` disappears from both sides at
      once. :class:`TestRendererCoversEverySignatureItIsGiven` is the
      assertion that is independent in KIND: it injects a synthetic tool the
      renderer has never heard of. Do not mistake this test for that one.
    """

    @pytest.mark.parametrize(
        'tool_name', _LIVE_REPORT_TOOL_NAMES, ids=list(_LIVE_REPORT_TOOL_NAMES)
    )
    def test_registered_tool_reaches_the_surface_its_classification_requires(self, tool_name):
        assert tool_name in RECON_REPORT_INSTRUCTIONS, (
            f'`{tool_name}` is registered on the live recon_report server but is named '
            'nowhere in RECON_REPORT_INSTRUCTIONS (server/recon_report.py) — a '
            'registered tool absent from RECON_REPORT_INSTRUCTIONS is invisible to any '
            'MCP client that reads the server instructions — add it there.'
        )
        if tool_name not in _SHARED_GUIDANCE_REPORT_TOOLS:
            return
        assert list(_iter_call_openers(render_recon_report_tool_guidance(), tool_name)), (
            f'`{tool_name}` is a shared-guidance tool but no call example for it appears '
            'in render_recon_report_tool_guidance()\'s output, so no stage agent is ever '
            'told it exists. Either render it, or classify it in '
            'HARNESS_CALLED_REPORT_TOOLS / STAGE_GATED_REPORT_TOOLS '
            '(server/recon_report.py).'
        )

    def test_delete_finding_regression_stays_closed(self):
        """delete_finding: registered and denied by no stage, but unadvertised.

        Asserted BY NAME, not only through the derived sets, so the fix cannot
        be quietly undone by reclassifying delete_finding as harness-called or
        stage-gated — which would satisfy every derived assertion in this
        module while putting the agent back exactly where task 3878 found it.
        """
        assert 'delete_finding' in _SHARED_GUIDANCE_REPORT_TOOLS, (
            'delete_finding is no longer classified as a shared-guidance tool. It is '
            'registered and appears in NO disallow list in cli_stage_runner.py, so every '
            'stage can call it; classifying it otherwise hides a callable tool from the '
            'agent, which is the exact regression task 3878 fixed.'
        )
        assert list(_iter_call_openers(render_recon_report_tool_guidance(), 'delete_finding')), (
            'the rendered guidance no longer shows a delete_finding call example — task '
            '3878 added it because an agent that filed a finding in error had no '
            'advertised way to retract it.'
        )

    def test_write_entity_standing_decision_regression_stays_closed(self):
        """write_entity_standing_decision: registered, but absent from the server listing.

        The mirror-image regression, and asserted by name for the mirror-image
        reason: it must stay documented in the stage-agnostic server
        instructions AND stay stage-gated, because Stage 1 and Stage 3 deny it
        via DISALLOW_RECON_REPORT_LEDGER_WRITES. Reclassifying it as
        shared-guidance would advertise a durable SQLite-ledger write to two
        stages that cannot make one.
        """
        assert 'write_entity_standing_decision' in RECON_REPORT_INSTRUCTIONS, (
            'write_entity_standing_decision has been dropped from '
            'RECON_REPORT_INSTRUCTIONS — task 3878 added it because it was the only '
            'registered tool the server-level listing never named.'
        )
        assert 'write_entity_standing_decision' in STAGE_GATED_REPORT_TOOLS, (
            'write_entity_standing_decision is no longer stage-gated. It is denied in '
            'Stage 1 and Stage 3 via DISALLOW_RECON_REPORT_LEDGER_WRITES '
            '(cli_stage_runner.py); if that is genuinely no longer true, the disallow '
            'list is what should have changed first.'
        )
