"""Parity test: the non-sandbox and sandbox Claude invocation paths must
build byte-identical argv for identical inputs (task 2465 dedup).

Drives both real code paths — shared.cli_invoke.invoke_claude_agent
(non-sandbox) and orchestrator.agents.invoke._invoke_claude_with_sandbox
(sandbox) — with the same inputs, capturing the argv each one hands to its
respective ``_run_subprocess``. RED until both paths route through the
shared ``build_claude_argv`` helper (step-4): today the sandbox fork still
assembles argv by hand and lacks the CLI-2.1.168 StructuredOutput deny-list
expansion, so the ``schema_with_wildcard_deny`` case diverges.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any
from unittest.mock import patch

import pytest

from shared.cli_invoke import _SubprocessResult, invoke_claude_agent

from orchestrator.agents.invoke import _invoke_claude_with_sandbox

_SANDBOX_SENTINEL_PREFIX = ['SANDBOX', '--']


def _make_subprocess_result(**overrides: Any) -> _SubprocessResult:
    """Build a minimal _SubprocessResult that _parse_claude_output can parse."""
    stdout = json.dumps({
        'result': 'ok',
        'is_error': False,
        'subtype': 'success',
        'cost_usd': 0.01,
        'duration_ms': 100,
        'num_turns': 1,
        'session_id': 'test-session',
    })
    defaults: dict[str, Any] = {
        'stdout': stdout,
        'stderr': '',
        'returncode': 0,
        'duration_ms': 100,
        'timed_out': False,
    }
    defaults.update(overrides)
    return _SubprocessResult(**defaults)


def _normalize(cmd: list[str]) -> list[str]:
    """Replace the value token after --system-prompt-file / --mcp-config with
    a fixed placeholder — those paths are nondeterministic (tempfile.mkstemp)
    and independently generated by each of the two driven paths below.
    """
    out: list[str] = []
    replace_next = False
    for tok in cmd:
        if replace_next:
            out.append('<TMP>')
            replace_next = False
            continue
        out.append(tok)
        if tok in ('--system-prompt-file', '--mcp-config'):
            replace_next = True
    return out


# Representative input sets driven through BOTH paths.  Keys match the
# common keyword surface of invoke_claude_agent and _invoke_claude_with_sandbox
# (excluding prompt/system_prompt/cwd, supplied by the drive helpers, and
# sandbox_modules/sandbox_wrap, which are path-specific).
CASES: dict[str, dict[str, Any]] = {
    'plain': {
        'model': 'opus',
        'max_turns': 50,
        'max_budget_usd': 5.0,
        'allowed_tools': None,
        'disallowed_tools': None,
        'mcp_config': None,
        'output_schema': None,
        'permission_mode': 'bypassPermissions',
        'effort': None,
        'resume_session_id': None,
        'session_id': None,
    },
    'resume': {
        'model': 'opus',
        'max_turns': 10,
        'max_budget_usd': 2.5,
        'allowed_tools': None,
        'disallowed_tools': None,
        'mcp_config': None,
        'output_schema': None,
        'permission_mode': 'bypassPermissions',
        'effort': None,
        'resume_session_id': 'resume-xyz',
        'session_id': None,
    },
    # The drift-exposing case: output_schema + disallowed_tools=['*'] must
    # trigger the CLI-2.1.168 deny-list expansion on BOTH paths.
    'schema_with_wildcard_deny': {
        'model': 'opus',
        'max_turns': 20,
        'max_budget_usd': 3.0,
        'allowed_tools': ['Read'],
        'disallowed_tools': ['*'],
        'mcp_config': {'mcpServers': {'foo': {'command': 'bar'}}},
        'output_schema': {'type': 'object'},
        'permission_mode': 'bypassPermissions',
        'effort': 'high',
        'resume_session_id': None,
        'session_id': 'sess-1',
    },
}


async def _drive_non_sandbox(inputs: dict[str, Any], cwd: Path) -> list[str]:
    """Invoke the non-sandbox path and capture the argv handed to _run_subprocess."""
    captured: list[list[str]] = []

    async def fake_run_subprocess(cmd: list[str], *args: Any, **kwargs: Any) -> _SubprocessResult:
        captured.append(list(cmd))
        return _make_subprocess_result()

    with patch('shared.cli_invoke._run_subprocess', side_effect=fake_run_subprocess):
        await invoke_claude_agent(
            prompt='hello',
            system_prompt='sys prompt',
            cwd=cwd,
            **inputs,
        )

    assert len(captured) == 1, f'expected exactly one subprocess invocation; got {captured!r}'
    return captured[0]


async def _drive_sandbox(inputs: dict[str, Any], cwd: Path) -> list[str]:
    """Invoke the sandbox path and capture the (unwrapped) argv handed to _run_subprocess."""
    captured: list[list[str]] = []

    async def fake_run_subprocess(cmd: list[str], *args: Any, **kwargs: Any) -> _SubprocessResult:
        captured.append(list(cmd))
        return _make_subprocess_result()

    def fake_wrap_command(cmd: list[str], cwd: Path, sandbox_modules: list[str]) -> list[str]:
        return _SANDBOX_SENTINEL_PREFIX + cmd

    with (
        patch('orchestrator.agents.sandbox_dispatch.resolve_active_backend', return_value='bwrap'),
        patch('orchestrator.agents.sandbox_dispatch.wrap_command', side_effect=fake_wrap_command),
        patch('orchestrator.agents.invoke._run_subprocess', side_effect=fake_run_subprocess),
    ):
        await _invoke_claude_with_sandbox(
            prompt='hello',
            system_prompt='sys prompt',
            cwd=cwd,
            sandbox_modules=['shared'],
            **inputs,
        )

    assert len(captured) == 1, f'expected exactly one subprocess invocation; got {captured!r}'
    argv = captured[0]
    prefix_len = len(_SANDBOX_SENTINEL_PREFIX)
    assert argv[:prefix_len] == _SANDBOX_SENTINEL_PREFIX, (
        f'expected sandbox argv to start with sentinel wrap {_SANDBOX_SENTINEL_PREFIX!r}; got {argv[:prefix_len + 2]!r}'
    )
    return argv[prefix_len:]


@pytest.mark.asyncio
@pytest.mark.parametrize('case_name,inputs', list(CASES.items()), ids=list(CASES.keys()))
async def test_non_sandbox_and_sandbox_argv_are_identical(
    case_name: str, inputs: dict[str, Any], tmp_path: Path,
) -> None:
    """Both invocation paths must build the same argv for identical inputs.

    Normalizes the nondeterministic temp-file tokens on both sides, then
    asserts structural equality — this is the signal that the two argv
    builders have converged on a single source of truth.
    """
    non_sandbox_argv = await _drive_non_sandbox(inputs, tmp_path / 'non-sandbox')
    sandbox_argv = await _drive_sandbox(inputs, tmp_path / 'sandbox')

    assert _normalize(non_sandbox_argv) == _normalize(sandbox_argv), (
        f'[{case_name}] argv diverged between non-sandbox and sandbox paths:\n'
        f'  non-sandbox={non_sandbox_argv!r}\n'
        f'  sandbox    ={sandbox_argv!r}'
    )
