"""Tests for ``GitOps._scrub_seeded_lane_target`` — deletes configured glob
subtrees under a CoW-seeded lane's ``target/`` so they regenerate per-lane
instead of carrying forward stale baked-in absolute paths from the shared
warm base (task 2315, BUG 3).

Incident: the warm-lane CoW seed base's ``target/`` directory can contain
generated artifacts (e.g. tauri permission autogen files) that embed an
ABSOLUTE path pointing back at the shared ``_merge-verify/target`` OUT_DIR
they were originally generated under. When a lane's ``target/`` is ``cp -a
--reflink``-seeded from that base (:meth:`GitOps._seed_warm_lane`), those
baked-in paths leak into every lane — silently pointing at the shared
location instead of the lane's own tree.

Fix by EXCLUSION rather than rewrite: after a successful seed, delete the
configured glob-matched subtrees so they regenerate fresh, per-lane, on
first use (no fragile string-substitution inside TOML/binary artifacts).
Driven by ``GitConfig.warm_lane_seed_scrub_globs``, defaulting to ``[]``
(opt-in, byte-identical by default).

This module builds up the fix from the bottom:
  step-7/8   — the ``_scrub_seeded_lane_target`` predicate/writer itself
  step-9/10  — the ``_seed_warm_lane`` rc==0 chokepoint wiring
"""
from __future__ import annotations

from pathlib import Path

import pytest

from orchestrator.config import GitConfig
from orchestrator.git_ops import GitOps, _run


def _git_config(**overrides) -> GitConfig:
    return GitConfig(
        main_branch='main',
        branch_prefix='task/',
        remote='origin',
        worktree_dir='.worktrees',
        push_after_advance=False,
        **overrides,
    )


def _git_ops(tmp_path: Path, **config_overrides) -> GitOps:
    project_root = tmp_path / 'project'
    project_root.mkdir(exist_ok=True)
    return GitOps(_git_config(**config_overrides), project_root)


def _write_autogen_residue(lane_dir: Path) -> Path:
    """Build target/debug/build/reify-gui/out/permissions/app/autogenerated/perms.toml
    whose text contains a baked absolute OUT_DIR path pointing at the
    shared _merge-verify/target base -- the CoW-leak residue under test.
    """
    autogen_dir = (
        lane_dir / 'target' / 'debug' / 'build' / 'reify-gui' / 'out'
        / 'permissions' / 'app' / 'autogenerated'
    )
    autogen_dir.mkdir(parents=True, exist_ok=True)
    perms_file = autogen_dir / 'perms.toml'
    perms_file.write_text(
        '# generated by tauri\n'
        'out_dir = "/home/build/.worktrees/_merge-verify/target/debug/build/reify-gui/out"\n'
    )
    return perms_file


def _write_sibling_artifact(lane_dir: Path) -> Path:
    """A sibling non-matching build artifact that must be RETAINED."""
    other_dir = lane_dir / 'target' / 'debug'
    other_dir.mkdir(parents=True, exist_ok=True)
    other = other_dir / 'other.rlib'
    other.write_text('unrelated build artifact\n')
    return other


class TestScrubSeededLaneTarget:
    """GitOps._scrub_seeded_lane_target(lane_dir) (task 2315, step-7/8)."""

    def test_configured_glob_deletes_matched_subtree_retains_sibling(
        self, tmp_path: Path,
    ):
        git_ops = _git_ops(
            tmp_path, warm_lane_seed_scrub_globs=['**/permissions/*/autogenerated'],
        )
        lane_dir = tmp_path / 'lane'
        lane_dir.mkdir()
        perms_file = _write_autogen_residue(lane_dir)
        other = _write_sibling_artifact(lane_dir)

        git_ops._scrub_seeded_lane_target(lane_dir)

        assert not perms_file.exists()
        assert not perms_file.parent.exists(), (
            'expected the matched autogenerated/ subtree to be removed entirely'
        )
        assert other.exists(), 'expected the sibling non-matching artifact to be retained'

    def test_default_config_is_a_no_op(self, tmp_path: Path):
        git_ops = _git_ops(tmp_path)  # warm_lane_seed_scrub_globs defaults to []
        assert git_ops.config.warm_lane_seed_scrub_globs == []
        lane_dir = tmp_path / 'lane'
        lane_dir.mkdir()
        perms_file = _write_autogen_residue(lane_dir)

        git_ops._scrub_seeded_lane_target(lane_dir)

        assert perms_file.exists(), 'default (opt-in-off) config must never scrub anything'

    def test_glob_matching_nothing_leaves_target_untouched_and_does_not_raise(
        self, tmp_path: Path,
    ):
        git_ops = _git_ops(
            tmp_path, warm_lane_seed_scrub_globs=['**/does-not-exist/*'],
        )
        lane_dir = tmp_path / 'lane'
        lane_dir.mkdir()
        perms_file = _write_autogen_residue(lane_dir)
        other = _write_sibling_artifact(lane_dir)

        git_ops._scrub_seeded_lane_target(lane_dir)  # must not raise

        assert perms_file.exists()
        assert other.exists()


# ---------------------------------------------------------------------------
# step-9/10: _seed_warm_lane rc==0 chokepoint wiring (end-to-end)
# ---------------------------------------------------------------------------


async def _init_repo(repo: Path) -> None:
    await _run(['git', 'init', '-b', 'main'], cwd=repo)
    await _run(['git', 'config', 'user.email', 'test@test.com'], cwd=repo)
    await _run(['git', 'config', 'user.name', 'Test'], cwd=repo)
    (repo / 'README.md').write_text('# Test\n')
    await _run(['git', 'add', '-A'], cwd=repo)
    await _run(['git', 'commit', '-m', 'Initial commit'], cwd=repo)


async def _make_registered_lane(repo: Path, lane_name: str = '_lane-0') -> Path:
    """Create a real worktree at <repo>/.worktrees/<lane_name> for seeding tests."""
    worktree_base = repo / '.worktrees'
    worktree_base.mkdir(parents=True, exist_ok=True)
    lane = worktree_base / lane_name
    await _run(
        ['git', 'worktree', 'add', '-b', f'task/{lane_name}', str(lane), 'HEAD'],
        cwd=repo,
    )
    return lane


def _drop_seed_script_with_autogen_residue(lane_dir: Path) -> Path:
    """Drop scripts/seed-warm-lane.sh into the lane's own tree (uncommitted,
    consistent with the lane-provides-its-own-script convention used by
    ``TestSeedWarmLane`` in test_warm_lane_pool.py).

    The stub's body simulates a real CoW seed that carries forward the
    baked-path OUT_DIR-leak residue under test (task 2315, BUG 3): it
    creates target/debug/build/reify-gui/out/permissions/app/autogenerated/
    perms.toml (containing an absolute path back at the shared
    _merge-verify/target base) under $2 (the lane_dir arg _seed_warm_lane
    passes), then exits 0.

    Returns the path to the created residue file.
    """
    scripts_dir = lane_dir / 'scripts'
    scripts_dir.mkdir(parents=True, exist_ok=True)
    script = scripts_dir / 'seed-warm-lane.sh'
    autogen_rel = 'target/debug/build/reify-gui/out/permissions/app/autogenerated'
    script.write_text(
        '#!/usr/bin/env bash\n'
        'set -e\n'
        f'mkdir -p "$2/{autogen_rel}"\n'
        f'cat > "$2/{autogen_rel}/perms.toml" <<EOF\n'
        '# generated by tauri\n'
        'out_dir = "/home/build/.worktrees/_merge-verify/target/debug/build/reify-gui/out"\n'
        'EOF\n'
        'exit 0\n'
    )
    script.chmod(0o755)
    return lane_dir / autogen_rel / 'perms.toml'


@pytest.mark.asyncio
class TestSeedWarmLaneScrubsOnSuccess:
    """_seed_warm_lane scrubs the seeded lane's target/ on rc==0 (step-9/10)."""

    async def test_seed_warm_lane_scrubs_autogen_residue_on_success(
        self, tmp_path: Path,
    ):
        repo = tmp_path / 'repo'
        repo.mkdir()
        await _init_repo(repo)
        lane = await _make_registered_lane(repo, '_lane-0')
        residue = _drop_seed_script_with_autogen_residue(lane)

        git_ops = GitOps(
            _git_config(warm_lane_seed_scrub_globs=['**/permissions/*/autogenerated']),
            repo,
        )

        rc = await git_ops._seed_warm_lane(lane, '--fresh-checkout')

        assert rc == 0, f'expected seed script to succeed, got rc={rc!r}'
        assert not residue.exists(), (
            'expected the baked-path autogen residue to be scrubbed after '
            'a successful seed'
        )
        assert not residue.parent.exists(), (
            'expected the matched autogenerated/ subtree to be removed entirely'
        )
        assert git_ops.pool_storage_present() is True, (
            'scrub must not disturb the .pool-root sentinel mark on rc==0'
        )
