"""Tests for ``GitOps._scrub_seeded_lane_target`` — deletes configured glob
subtrees under a CoW-seeded lane's ``target/`` so they regenerate per-lane
instead of carrying forward stale baked-in absolute paths from the shared
warm base (task 2315, BUG 3).

Incident: the warm-lane CoW seed base's ``target/`` directory can contain
generated artifacts (e.g. tauri permission autogen files) that embed an
ABSOLUTE path pointing back at the shared ``_merge-verify/target`` OUT_DIR
they were originally generated under. When a lane's ``target/`` is ``cp -a
--reflink``-seeded from that base (:meth:`GitOps._seed_warm_lane`), those
baked-in paths leak into every lane — silently pointing at the shared
location instead of the lane's own tree.

Fix by EXCLUSION rather than rewrite: after a successful seed, delete the
configured glob-matched subtrees so they regenerate fresh, per-lane, on
first use (no fragile string-substitution inside TOML/binary artifacts).
Driven by ``GitConfig.warm_lane_seed_scrub_globs``, defaulting to ``[]``
(opt-in, byte-identical by default).

This module builds up the fix from the bottom:
  step-7/8   — the ``_scrub_seeded_lane_target`` predicate/writer itself
  step-9/10  — the ``_seed_warm_lane`` rc==0 chokepoint wiring
"""
from __future__ import annotations

from pathlib import Path

from orchestrator.config import GitConfig
from orchestrator.git_ops import GitOps


def _git_config(**overrides) -> GitConfig:
    return GitConfig(
        main_branch='main',
        branch_prefix='task/',
        remote='origin',
        worktree_dir='.worktrees',
        push_after_advance=False,
        **overrides,
    )


def _git_ops(tmp_path: Path, **config_overrides) -> GitOps:
    project_root = tmp_path / 'project'
    project_root.mkdir(exist_ok=True)
    return GitOps(_git_config(**config_overrides), project_root)


def _write_autogen_residue(lane_dir: Path) -> Path:
    """Build target/debug/build/reify-gui/out/permissions/app/autogenerated/perms.toml
    whose text contains a baked absolute OUT_DIR path pointing at the
    shared _merge-verify/target base -- the CoW-leak residue under test.
    """
    autogen_dir = (
        lane_dir / 'target' / 'debug' / 'build' / 'reify-gui' / 'out'
        / 'permissions' / 'app' / 'autogenerated'
    )
    autogen_dir.mkdir(parents=True, exist_ok=True)
    perms_file = autogen_dir / 'perms.toml'
    perms_file.write_text(
        '# generated by tauri\n'
        'out_dir = "/home/build/.worktrees/_merge-verify/target/debug/build/reify-gui/out"\n'
    )
    return perms_file


def _write_sibling_artifact(lane_dir: Path) -> Path:
    """A sibling non-matching build artifact that must be RETAINED."""
    other_dir = lane_dir / 'target' / 'debug'
    other_dir.mkdir(parents=True, exist_ok=True)
    other = other_dir / 'other.rlib'
    other.write_text('unrelated build artifact\n')
    return other


class TestScrubSeededLaneTarget:
    """GitOps._scrub_seeded_lane_target(lane_dir) (task 2315, step-7/8)."""

    def test_configured_glob_deletes_matched_subtree_retains_sibling(
        self, tmp_path: Path,
    ):
        git_ops = _git_ops(
            tmp_path, warm_lane_seed_scrub_globs=['**/permissions/*/autogenerated'],
        )
        lane_dir = tmp_path / 'lane'
        lane_dir.mkdir()
        perms_file = _write_autogen_residue(lane_dir)
        other = _write_sibling_artifact(lane_dir)

        git_ops._scrub_seeded_lane_target(lane_dir)

        assert not perms_file.exists()
        assert not perms_file.parent.exists(), (
            'expected the matched autogenerated/ subtree to be removed entirely'
        )
        assert other.exists(), 'expected the sibling non-matching artifact to be retained'

    def test_default_config_is_a_no_op(self, tmp_path: Path):
        git_ops = _git_ops(tmp_path)  # warm_lane_seed_scrub_globs defaults to []
        assert git_ops.config.warm_lane_seed_scrub_globs == []
        lane_dir = tmp_path / 'lane'
        lane_dir.mkdir()
        perms_file = _write_autogen_residue(lane_dir)

        git_ops._scrub_seeded_lane_target(lane_dir)

        assert perms_file.exists(), 'default (opt-in-off) config must never scrub anything'

    def test_glob_matching_nothing_leaves_target_untouched_and_does_not_raise(
        self, tmp_path: Path,
    ):
        git_ops = _git_ops(
            tmp_path, warm_lane_seed_scrub_globs=['**/does-not-exist/*'],
        )
        lane_dir = tmp_path / 'lane'
        lane_dir.mkdir()
        perms_file = _write_autogen_residue(lane_dir)
        other = _write_sibling_artifact(lane_dir)

        git_ops._scrub_seeded_lane_target(lane_dir)  # must not raise

        assert perms_file.exists()
        assert other.exists()
