"""Replay the committed prefix corpus through the C1 detector.

WHAT THIS PINS, AND WHAT IT DOES NOT. Every expectation in the fixture was
MACHINE-GENERATED by ``uuid_prefix_corpus_extract.py`` from the detector's own
answers, so agreeing with them pins REGRESSION-STABILITY and DETERMINISM — not
correctness. Correctness is pinned by the hand-authored grammar rows in
``test_uuid_prefix.py``, which a human decided; this file catches the day a
refactor quietly changes what the grammar accepts across 200+ real contexts.
The markup corpus states the same split, and it is worth restating here because
a machine-generated corpus that claims correctness is worse than none.

One assertion IS non-circular and does not consult the stored expectation at
all: every row whose token is immediately preceded by ``-`` or ``_`` in the
window must yield NO token at that span, re-derived from the window text. A
detector that silently dropped the glue rule could pass every other assertion
here by regenerating its own expectations; it cannot pass that one.

SELF-CONTAINED. This reads ``fixtures/uuid_prefix_corpus.jsonl`` and nothing
else — no pickles, no live store, no network. The position paper's
``occurrences.pkl`` lived in a ``/tmp`` scratch directory and its scan is not
re-runnable (it read live stores and read-only snapshots that no longer exist),
so the committed file is the durable artifact and must outlive its source.

This test replays through the DETECTOR only. The C3 policy matrix is the
in-process FastMCP harness's job in ``test_uuid_prefix_guard.py``: driving 200+
rows through a live ``Client`` would add minutes and make no claim the
hand-authored matrix cells do not already make.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
import uuid_prefix_corpus_extract as extract

from shared.uuid_prefix import find_prefix_tokens

#: The floor the plan names. Asserted as a MINIMUM, never a fixed count: a
#: better corpus must never read as a regression.
MINIMUM_ROWS = 200

CORPUS_PATH = extract.DEFAULT_OUT


@pytest.fixture(scope='module')
def corpus() -> list[dict[str, Any]]:
    return extract.load_corpus(CORPUS_PATH)


def detected(window: str) -> list[dict[str, Any]]:
    """The detector's answer for one window, in the corpus's stored shape."""
    return [
        {'token': token.token, 'start': token.start, 'end': token.end}
        for token in find_prefix_tokens({'content': window})
    ]


# ---------------------------------------------------------------------------
# The corpus itself.
# ---------------------------------------------------------------------------


class TestTheCorpusIsWellFormed:
    def test_it_has_at_least_the_minimum_rows(self, corpus) -> None:
        assert len(corpus) >= MINIMUM_ROWS

    def test_every_row_carries_exactly_the_declared_keys(self, corpus) -> None:
        """One declared schema, checked per row, so a drifted writer is loud."""
        for row in corpus:
            assert set(row) == set(extract.ROW_KEYS), row

    def test_no_row_has_its_token_at_window_index_zero(self, corpus) -> None:
        """The +/-40 truncation cut the true predecessor for those rows.

        Their glue verdict is UNKNOWABLE, so the extractor drops them rather
        than storing a guess as an expectation.
        """
        assert [row for row in corpus if row['offset'] == 0] == []

    def test_every_row_finds_its_token_at_its_recorded_offset(self, corpus) -> None:
        """Provenance check: the offset really does address the stored token."""
        for row in corpus:
            token = row['token']
            assert row['window'][row['offset'] : row['offset'] + len(token)] == token, row


# ---------------------------------------------------------------------------
# Coverage — each declared stratum populated, never a fixed count.
# ---------------------------------------------------------------------------


class TestEveryDeclaredStratumIsPopulated:
    @pytest.mark.parametrize('paper_class', extract.PAPER_CLASSES)
    def test_paper_class(self, corpus, paper_class: str) -> None:
        assert [row for row in corpus if row['token_class'] == paper_class] != []

    @pytest.mark.parametrize('glue', extract.GLUES)
    def test_glue(self, corpus, glue: str) -> None:
        assert [row for row in corpus if row['glue'] == glue] != []

    @pytest.mark.parametrize('kind', extract.KINDS)
    def test_kind(self, corpus, kind: str) -> None:
        assert [row for row in corpus if row['kind'] == kind] != []

    def test_the_full_uuid_stratum_carries_no_paper_class(self, corpus) -> None:
        """The paper classified 8-hex tokens; a uuid36 row has no class to carry."""
        uuid_rows = [row for row in corpus if row['kind'] == 'uuid36']
        assert uuid_rows != []
        assert all(row['token_class'] is None for row in uuid_rows)


# ---------------------------------------------------------------------------
# Replay.
# ---------------------------------------------------------------------------


class TestTheDetectorStillAgreesWithEveryRow:
    def test_the_rows_own_span(self, corpus) -> None:
        """Is THAT EXACT span a token — the assertion the glue strata exist for."""
        for row in corpus:
            span = (row['offset'], row['offset'] + len(row['token']))
            found = any((t['start'], t['end']) == span for t in detected(row['window']))
            assert found == row['expected_own_span'], row

    def test_the_full_document_ordered_tuple(self, corpus) -> None:
        """Regression stability for the whole window, not just the paper's span."""
        for row in corpus:
            assert detected(row['window']) == row['expected_tokens'], row

    def test_replaying_the_whole_corpus_twice_is_identical(self, corpus) -> None:
        """``find_prefix_tokens`` is pure, so a second pass cannot differ."""
        first = [detected(row['window']) for row in corpus]
        second = [detected(row['window']) for row in corpus]
        assert first == second


class TestTheGlueRuleReDerivedFromTheWindow:
    """The one NON-CIRCULAR assertion: it never reads a stored expectation.

    A detector that dropped the glue rule could regenerate the whole corpus and
    pass every other test in this file. It cannot pass this one, because the
    verdict here is derived from the window text — ``recon-3f2a9c1e`` and
    ``episode_74b902f8`` are composite ids, not citations, and 29% of the noise
    class is exactly that shape.
    """

    def test_a_glued_token_is_never_reported_at_its_own_span(self, corpus) -> None:
        glued = [row for row in corpus if row['window'][row['offset'] - 1] in '-_']
        assert len(glued) >= 2, 'the corpus must carry both glue characters'
        for row in glued:
            span = (row['offset'], row['offset'] + len(row['token']))
            assert all((t['start'], t['end']) != span for t in detected(row['window'])), row

    def test_the_glue_column_agrees_with_the_window_text(self, corpus) -> None:
        """The stored stratum label is derived, not asserted — so check it."""
        for row in corpus:
            preceding = row['window'][row['offset'] - 1]
            expected = {'-': 'hyphen', '_': 'underscore'}.get(preceding, 'plain')
            assert row['glue'] == expected, row


# ---------------------------------------------------------------------------
# Serialization.
# ---------------------------------------------------------------------------


class TestTheCommittedFileIsExactlyWhatTheWriterEmits:
    """Byte-identical round-tripping, which is what makes a re-run reviewable.

    A regenerated corpus whose only diff is key order or spacing would bury the
    rows that actually changed.
    """

    def test_reserializing_the_parsed_corpus_reproduces_the_file(
        self, corpus, tmp_path: Path
    ) -> None:
        out = tmp_path / 'roundtrip.jsonl'
        extract.write_corpus(corpus, out)
        assert out.read_bytes() == Path(CORPUS_PATH).read_bytes()

    def test_writing_the_same_records_twice_is_byte_identical(
        self, corpus, tmp_path: Path
    ) -> None:
        first, second = tmp_path / 'a.jsonl', tmp_path / 'b.jsonl'
        extract.write_corpus(corpus, first)
        extract.write_corpus(corpus, second)
        assert first.read_bytes() == second.read_bytes()

    def test_the_committed_file_carries_no_literal_opening_angle_bracket(self) -> None:
        """Every ``\\x3c`` is escaped, so an agent re-emitting a row is safe.

        The markup corpus is written under the same rule and states why: a row
        quoted back into a tool call must not carry an envelope literal.
        """
        assert '\x3c' not in Path(CORPUS_PATH).read_text(encoding='utf-8')

    def test_the_escape_decodes_transparently(self, corpus) -> None:
        line = json.dumps(corpus[0], sort_keys=True, separators=(', ', ': '))
        assert json.loads(line.replace('\x3c', '\\u003c')) == corpus[0]
