#!/usr/bin/env python3
"""Extract the toolcall-markup specimen corpus from the agent-transcript archive.

PRD ``plans/toolcall-markup-containment-prd.md`` task alpha, boundary row B13.

WHAT THIS ANSWERS
-----------------
``shared.toolcall_markup.repair`` has to be pinned against REAL corrupted calls,
not invented ones. This module walks the orchestrator's archived agent
transcripts, collects every ``tool_use`` parameter matching the PRD's collection
predicate, and emits one JSONL record per specimen carrying the value, the
call's shape, and the outcome ``repair`` produces for it today.

The emitted file — ``shared/tests/fixtures/toolcall_markup_corpus.jsonl`` — is
the DURABLE artefact. Once committed it has no further dependency on the
archive, which is retention-bounded and will rotate the specimens away (PRD
section 11.4). Re-running this module is only needed to take a fresh snapshot.

WHAT THE CORPUS IS AND IS NOT
-----------------------------
The ``expected_outcome`` column is machine-generated BY the implementation it
pins, so the replay proves regression-stability and determinism, NOT
correctness. Correctness is pinned separately and first by the hand-authored
specimen tests in ``test_toolcall_markup.py``, which were written from the PRD's
parsed-input column before this corpus existed. Two checks in the replay are
non-circular by construction and are the load-bearing ones: the D5 structural
invariant, and re-deriving the collection predicate over every stored value.

HOW IT READS THE ARCHIVE
------------------------
Through ``legibility.inventory.iter_json_lines``, THE low-level streaming
transcript reader, rather than a reader rolled here. That buys the documented
line/file split — a corrupt LINE degrades silently, an unreadable FILE raises
``OSError`` and is skipped, counted and logged (:class:`WalkReport`) — with one
answer to "which exceptions mean unreadable", not a second copy of it.

An earlier version gated each line on a cheap ``'tool_use' in line`` substring
check before ``json.loads``. That is incompatible with the canonical reader,
which parses every line, and it was MEASURED not to matter for a tool that runs
once per snapshot: over 40 files / 17.1 MB / 5670 lines, prefilter-only was
0.16s against 0.78s parsing every line (4.9x), and a full run over the live
5703-file archive takes 1m35s wall (32s CPU). Roughly 80 seconds, once. Do not
reintroduce the prefilter to buy them back.

Run it as::

    uv run --project shared python tests/toolcall_markup_corpus_extract.py \\
        --archive-root /home/leo/src/dark-factory/data/orchestrator/agent-transcripts \\
        --out tests/fixtures/toolcall_markup_corpus.jsonl

## Sentinel-literal hazard — DO NOT "helpfully" un-escape these

Every envelope literal here is spelled with the ``\\x3c`` escape for ``<``, per
``fused_memory/utils/toolcall_xml_leak.py`` lines 77-86, and the emitted JSONL
escapes every ``<`` as its ``\\u003c`` JSON escape. That is not decoration: PRD
G6 explicitly anticipates a future agent hand-editing an expectation row, and it
must be able to do so without emitting an envelope literal inside its own
tool-call argument — which is the very defect this corpus documents. ``\\u003c``
is standard JSON, decoded transparently by ``json.loads``.
"""
from __future__ import annotations

import argparse
import dataclasses
import json
import logging
import re
import sys
from collections.abc import Collection, Iterator, Sequence
from pathlib import Path
from typing import Any, NamedTuple

_SRC = Path(__file__).resolve().parents[1] / 'src'
if str(_SRC) not in sys.path:  # pragma: no cover — bare-interpreter bootstrap
    sys.path.insert(0, str(_SRC))

# `legibility` is a namespace package under repo-root scripts/ — no __init__.py,
# installed nowhere, and not on shared's pytest `pythonpath`. This insert is the
# only way the canonical reader imports at all, so it runs at module scope
# rather than under a __main__ guard. Idempotent and guarded — the idiom is
# copied verbatim from fused-memory/scripts/memory_eval_transcript_corpus.py,
# the other cross-package consumer of the same reader.
#
# No layering cycle: scripts/legibility/inventory.py is stdlib-only and imports
# nothing from `shared`.
_SCRIPTS_ROOT = Path(__file__).resolve().parents[2] / 'scripts'
if _SCRIPTS_ROOT.exists() and str(_SCRIPTS_ROOT) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_ROOT))

# The `# type: ignore[reportMissingImports]` is not a defect being papered over:
# this resolves at RUNTIME via the insert above, but pyright is invoked from
# shared/ whose extraPaths cannot see repo-root scripts/. Same situation, same
# idiom, as memory_eval_transcript_corpus.py's.
from legibility.inventory import iter_json_lines  # type: ignore[reportMissingImports]  # noqa: E402

from shared.toolcall_markup import repair  # noqa: E402

_LOG = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# The collection predicate — PRD section 2, line 35, verbatim.
# ---------------------------------------------------------------------------

#: ``\x3c/invoke>\s*$`` — the total-drift tail, which the parser terminated at
#: the invoke closer because it never found the closer it wanted.
_PREDICATE_INVOKE_TAIL = re.compile(r'\x3c/invoke>\s*$')

#: ``\x3c/[A-Za-z_]\w*>\s*\x3cparameter\s+name="[^"]+">`` — the partial-drift
#: tail, where a name-echoing closer is followed by a canonical opener. The
#: whitespace requirement is what keeps ordinary prose that quotes a closing tag
#: out of the corpus.
_PREDICATE_MISCLOSE_THEN_OPENER = re.compile(
    r'\x3c/[A-Za-z_]\w*>\s*\x3cparameter\s+name="[^"]+">'
)

#: Repaired values keep at most this many characters of lead-in. Applied
#: unconditionally BY RULE rather than "if it looks big", so the output is
#: deterministic (PRD section 11.3).
LEAD_IN_CHARS = 200

#: The two legal values of a record's ``expected_outcome``.
OUTCOME_REPAIRED = 'repaired'
OUTCOME_UNREPAIRABLE = 'unrepairable'

#: Every key a corpus record carries. Pinned here so the writer, the loader and
#: the replay test all agree on one schema.
RECORD_KEYS = (
    'tool',
    'param',
    'supplied',
    'value',
    'expected_outcome',
    'expected_recovered',
    'schema_params',
    'tool_use_id',
    'truncated',
    'original_length',
)


def matches_collection_predicate(value: object) -> bool:
    """Is *value* a specimen? PRD section 2 line 35, stated exactly.

    A string-valued parameter matching ``\\x3c/invoke>\\s*$`` **or**
    ``\\x3c/[A-Za-z_]\\w*>\\s*\\x3cparameter\\s+name="[^"]+">``.

    Non-strings are not specimens and return ``False`` rather than raising, so
    the walker can hand it every parameter value it meets.
    """
    if not value or not isinstance(value, str):
        return False
    if _PREDICATE_INVOKE_TAIL.search(value) is not None:
        return True
    return _PREDICATE_MISCLOSE_THEN_OPENER.search(value) is not None


# ---------------------------------------------------------------------------
# Walking the archive.
# ---------------------------------------------------------------------------


def iter_transcript_files(root: Path | str) -> Iterator[Path]:
    """Yield every ``.jsonl.gz`` under *root*, RECURSIVELY, in sorted order.

    THE WALK MUST RECURSE. Measured 2026-08-08 (prerequisite P3): the archive
    nests its leaves two directories below the root —
    ``<root>/<task_id>/<project-dir>/<uuid>.jsonl.gz``, 710 task dirs, 5201
    leaves, 551 MB. A top-level ``*.jsonl.gz`` glob returns ZERO files, which
    would produce a silently empty corpus that looks like a clean run.

    A missing root yields nothing rather than raising: an archive that has been
    rotated away is a legitimate state for a caller that only wants a count.
    """
    root = Path(root)
    if not root.is_dir():
        return
    yield from sorted(path for path in root.rglob('*.jsonl.gz') if path.is_file())


class Candidate(NamedTuple):
    """One ``tool_use`` parameter that matched the collection predicate."""

    tool_use_id: str
    tool: str
    param: str
    supplied: tuple[str, ...]
    value: str


@dataclasses.dataclass
class WalkReport:
    """What one archive walk actually managed to read.

    The archive is live-written AND concurrently pruned by
    ``scripts/gc_agent_transcripts.py``, so a half-written or half-removed leaf
    is an expected state, not a theoretical one. Skipping it silently would let
    the corpus shrink without anyone noticing, which is the degradation the
    project's loud-over-silent norm exists to prevent — hence a count and the
    offending paths, not just a shrug.
    """

    #: Every ``.jsonl.gz`` the recursive walk found.
    files_walked: int = 0
    #: Those it read to the end. ``files_walked - files_read == len(unreadable)``.
    files_read: int = 0
    #: ``(path, "ExceptionType: message")`` per unreadable file, walk order.
    unreadable: list[tuple[str, str]] = dataclasses.field(default_factory=list)


def iter_tool_use_blocks(path: Path) -> Iterator[dict[str, Any]]:
    """Yield the ``tool_use`` blocks of one gzipped transcript, streaming.

    Delegates the read to ``legibility.inventory.iter_json_lines`` — THE
    low-level streaming transcript reader, already gz-transparent — rather than
    re-rolling one here. Everything this function still does is a STRUCTURAL
    shape check on already-parsed JSON.

    That reader's contract, which callers here depend on: a blank or corrupt
    LINE degrades silently, an unreadable FILE raises ``OSError``. The split is
    the accounting :class:`WalkReport` needs — a truncated trailing line, which
    every fire-and-forget writer eventually produces, must not inflate the
    unreadable-file count into a false alarm. All four unreadable-file shapes
    arrive as ``OSError`` because ``inventory.as_unreadable_file_error``
    normalizes them at the reader seam.

    Note this reads under STRICT UTF-8. The hand-rolled predecessor passed
    ``errors='replace'``, which does not skip anything — it turns a corrupt byte
    into U+FFFD and lets the record through, so a replacement character would be
    committed to the corpus as if it were real harness output.

    The caller must consume this generator inside its own ``except OSError``;
    the raise happens lazily, at read time, not at call time.
    """
    for record in iter_json_lines(path):
        message = record.get('message')
        if not isinstance(message, dict):
            continue
        content = message.get('content')
        if not isinstance(content, list):
            continue
        for block in content:
            if isinstance(block, dict) and block.get('type') == 'tool_use':
                yield block


def iter_candidates(
    root: Path | str,
    report: WalkReport | None = None,
) -> Iterator[tuple[Candidate | None, str, tuple[str, ...]]]:
    """Yield ``(candidate_or_None, tool, observed_keys)`` for every tool_use block.

    ``observed_keys`` is emitted for EVERY block, matched or not, because
    ``schema_params`` is the union of keys a tool was seen to be called with
    across the whole archive — a clean call of the same tool contributes just as
    much schema evidence as a corrupted one, and in practice contributes almost
    all of it (a dropped parameter is by definition absent from the corrupted
    call's own key set, so only clean calls can testify that it exists).

    An unreadable file is SKIPPED, logged at WARNING and recorded in *report*
    rather than aborting the walk. The handler is deliberately narrow — plain
    ``except OSError``, around the per-file consumption only — and deliberately
    NOT widened to also catch ``EOFError``/``zlib.error``/``UnicodeDecodeError``:
    ``inventory.as_unreadable_file_error`` is the ONE answer to "which
    exceptions mean an unreadable file", and a second answer at each call site
    is precisely what INV-5 forbids. This task, of all tasks, must not write one.
    """
    report = report if report is not None else WalkReport()
    for path in iter_transcript_files(root):
        report.files_walked += 1
        try:
            # Materialized per FILE, not per archive: the raise is lazy, so the
            # handler has to wrap the consumption, and this is the same shape
            # memory_eval_transcript_corpus.py uses. Peak memory stays bounded
            # by one transcript's tool_use blocks.
            blocks = list(iter_tool_use_blocks(path))
        except OSError as exc:
            detail = f'{type(exc).__name__}: {exc}'
            report.unreadable.append((str(path), detail))
            _LOG.warning('skipping unreadable transcript %s (%s)', path, detail)
            continue
        report.files_read += 1
        for block in blocks:
            tool = block.get('name')
            arguments = block.get('input')
            block_id = block.get('id')
            if not isinstance(tool, str) or not isinstance(arguments, dict):
                continue
            keys = tuple(sorted(str(key) for key in arguments))
            matched: Candidate | None = None
            if isinstance(block_id, str):
                for param, value in sorted(arguments.items()):
                    if matches_collection_predicate(value):
                        matched = Candidate(
                            tool_use_id=block_id,
                            tool=tool,
                            param=str(param),
                            supplied=keys,
                            value=value,
                        )
                        break
            yield (matched, tool, keys)


# ---------------------------------------------------------------------------
# Truncation.
# ---------------------------------------------------------------------------


def apply_truncation(
    value: str,
    param: str,
    schema_params: Collection[str],
    supplied: Collection[str],
) -> tuple[str, bool]:
    """Return ``(stored_value, truncated)`` for one specimen (PRD section 11.3).

    A REPAIRED value longer than the bound is stored as up to
    :data:`LEAD_IN_CHARS` characters of lead-in plus everything from the
    mis-close onward. An UNREPAIRABLE value is stored VERBATIM however long,
    because those are the specimens a future improvement gets adjudicated
    against and truncating them would destroy the evidence.

    The extractor REFUSES to emit a truncated record whose repair result differs
    from the full value's — same recovered names, and a ``clean_value`` equal to
    the stored lead-in. Without that check the corpus would pin a fiction: an
    outcome the real value never produced.

    It refuses on a second, independent ground: a truncated value that no longer
    satisfies the collection predicate. Both predicate alternatives ``search``
    the WHOLE value, so a specimen collected on a mis-close-then-opener sequence
    sitting mid-value, while ``repair`` accepts a LATER mis-close, would be
    truncated to a stored value the corpus's own definition would never have
    collected. Storing it verbatim keeps the replay test's predicate
    re-derivation an honest non-circular check rather than something the
    extractor has to be exempted from.

    RETAINED THOUGH BELIEVED UNREACHABLE, and deliberately so. That second
    ground was measured live once — 1 specimen of the 473 in the 2026-08-08
    snapshot — but ``repair``'s prefix-clean post-condition (added under review
    fix 2) now refuses that whole shape outright, at the ``result is None``
    branch above, and no record in the regenerated corpus reaches this check.
    The reason is that BOTH predicate alternatives are built from envelope
    literals, so a predicate match strictly before an accepted mis-close would
    poison the prefix and ``repair`` would decline. The guard stays because it
    does NOT depend on that argument: it is the extractor's own check that what
    it emits satisfies the corpus's definition, and a future task widening the
    collection predicate with a non-envelope alternative would make it live
    again without anyone re-deriving the coupling.
    """
    result = repair(value, param, schema_params, supplied)
    if result is None:
        return (value, False)
    if len(result.clean_value) <= LEAD_IN_CHARS:
        return (value, False)

    lead_in = result.clean_value[-LEAD_IN_CHARS:]
    stored = lead_in + value[len(result.clean_value):]

    replayed = repair(stored, param, schema_params, supplied)
    if replayed is None:
        return (value, False)
    if replayed.clean_value != lead_in:
        return (value, False)
    if sorted(replayed.recovered) != sorted(result.recovered):
        return (value, False)
    if not matches_collection_predicate(stored):
        return (value, False)
    return (stored, True)


# ---------------------------------------------------------------------------
# Records.
# ---------------------------------------------------------------------------


def build_record(candidate: Candidate, schema_params: Sequence[str]) -> dict[str, Any]:
    """Build one corpus record, stamping the outcome ``repair`` produces today.

    ``expected_outcome`` and ``expected_recovered`` are computed from the STORED
    value, so the committed file is replayable from itself with no reference to
    the original — which is the whole point of PRD section 11.4.
    """
    stored, truncated = apply_truncation(
        candidate.value,
        param=candidate.param,
        schema_params=schema_params,
        supplied=candidate.supplied,
    )
    result = repair(stored, candidate.param, schema_params, candidate.supplied)
    return {
        'tool': candidate.tool,
        'param': candidate.param,
        'supplied': list(candidate.supplied),
        'value': stored,
        'expected_outcome': OUTCOME_UNREPAIRABLE if result is None else OUTCOME_REPAIRED,
        'expected_recovered': [] if result is None else sorted(result.recovered),
        'schema_params': list(schema_params),
        'tool_use_id': candidate.tool_use_id,
        'truncated': truncated,
        'original_length': len(candidate.value),
    }


def extract(root: Path | str, report: WalkReport | None = None) -> list[dict[str, Any]]:
    """Walk *root* and return the corpus, deduped and in a stable total order.

    Two passes over one streamed walk: candidates are collected while the
    per-tool observed-key union accumulates, then records are built once every
    tool's schema is known. Dedup is by ``tool_use`` block id — the same block
    really does appear in more than one file (resumed sessions, re-archival) —
    and the order is by that id, which is a stable total order because ids are
    unique.

    Pass a :class:`WalkReport` to learn what the walk could and could not read;
    unreadable files are skipped either way, and logged at WARNING either way.
    """
    candidates: dict[str, Candidate] = {}
    observed: dict[str, set[str]] = {}
    for matched, tool, keys in iter_candidates(root, report):
        observed.setdefault(tool, set()).update(keys)
        if matched is not None:
            candidates.setdefault(matched.tool_use_id, matched)
    return [
        build_record(candidate, sorted(observed.get(candidate.tool, ())))
        for _, candidate in sorted(candidates.items())
    ]


# ---------------------------------------------------------------------------
# Serialization.
# ---------------------------------------------------------------------------


def write_corpus(records: Sequence[dict[str, Any]], out: Path | str) -> None:
    """Write *records* as JSONL with every ``<`` escaped as ``\\u003c``.

    ``sort_keys=True`` and the fixed separators make repeated runs over equal
    input byte-identical, which is the extractor half of boundary row B13.
    """
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        json.dumps(record, sort_keys=True, separators=(', ', ': ')).replace('\x3c', '\\u003c')
        for record in records
    ]
    out.write_text(''.join(line + '\n' for line in lines), encoding='utf-8')


def load_corpus(path: Path | str) -> list[dict[str, Any]]:
    """Read a corpus JSONL back. ``\\u003c`` decodes transparently."""
    text = Path(path).read_text(encoding='utf-8')
    return [json.loads(line) for line in text.splitlines() if line.strip()]


# ---------------------------------------------------------------------------
# CLI.
# ---------------------------------------------------------------------------

_DEFAULT_ARCHIVE = (
    Path(__file__).resolve().parents[2] / 'data' / 'orchestrator' / 'agent-transcripts'
)
_DEFAULT_OUT = Path(__file__).resolve().parent / 'fixtures' / 'toolcall_markup_corpus.jsonl'


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description='Extract the toolcall-markup specimen corpus from archived transcripts.',
        epilog=(
            'The archive is gitignored and NOT per-worktree, so from inside a task '
            'worktree pass --archive-root pointing at the main checkout. A run that '
            'walks zero files is reported loudly rather than writing an empty corpus.'
        ),
    )
    parser.add_argument('--archive-root', type=Path, default=_DEFAULT_ARCHIVE)
    parser.add_argument('--out', type=Path, default=_DEFAULT_OUT)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)

    walked = sum(1 for _ in iter_transcript_files(args.archive_root))
    if walked == 0:
        # LOUD, not silent: a zero-file walk is the failure mode the nested
        # archive layout produces when the walker forgets to recurse, and an
        # empty corpus would otherwise read as a clean snapshot.
        print(
            f'ERROR: no .jsonl.gz found under {args.archive_root} — '
            'nothing written (check --archive-root, and that the walk recurses)',
            file=sys.stderr,
        )
        return 1

    report = WalkReport()
    records = extract(args.archive_root, report)

    for path, detail in report.unreadable:
        print(f'skipped unreadable transcript {path} ({detail})', file=sys.stderr)
    if report.files_read == 0:
        # LOUD, one level in from the zero-files-walked guard above: files WERE
        # found, so that guard passed, and without this one an archive whose
        # every leaf is half-written would overwrite the committed corpus with
        # an empty file and exit 0.
        print(
            f'ERROR: all {report.files_walked} transcript files under '
            f'{args.archive_root} were unreadable — nothing written',
            file=sys.stderr,
        )
        return 1

    write_corpus(records, args.out)
    repaired = sum(1 for r in records if r['expected_outcome'] == OUTCOME_REPAIRED)
    truncated = sum(1 for r in records if r['truncated'])
    print(
        f'walked {report.files_walked} transcript files under {args.archive_root} '
        f'({report.files_read} read, {len(report.unreadable)} unreadable)\n'
        f'wrote {len(records)} specimens to {args.out} '
        f'({repaired} repaired, {len(records) - repaired} unrepairable, '
        f'{truncated} truncated, {args.out.stat().st_size} bytes)',
        file=sys.stderr,
    )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
